### ISSUE TITLE
QG4 System Team checks (Release 3.1)

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/item-relationship-service#100]
# QG checks

## Please keep this issue open until QG4 is concluded!

Product Name: Item Relationship Service
Product Owner: Johannes Zahn
Dev SPOC: @ds-jhartmann 
Helm Chart Version: `5.0.10`
App Version: `2.4.1`
QG4 Approval: no

##### TRG 1.01
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1
- [x] an appropriate `README.md` file
###### TRG 1.02
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2
- [x] an appropriate `INSTALL.md`
###### TRG 1.03
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3
- [x] an appropriate `CHANGELOG.md`
  - [x] the versioning itself follows [semantic versioning](https://semver.org/)
##### TRG 2.01
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1
- [x] default branch is named `main`
##### TRG 2.03
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3
- [x] `/docs` directory contains detailed product related documentation for the Tractus-X product
- [x] `/charts` directory contains the Helm chart for the Tractus-X product IF available
- [x] `AUTHORS.md` file (optional)
- [x] `CODE_OF_CONDUCT.md` file
- [x] `CONTRIBUTING.md` file
- [x] `DEPENDENCIES` file(s) with up to date content (Dash tool generated)
- [x] `LICENSE` file
- [x] `NOTICE.md` file
- [x] `SECURITY.md` file
##### TRG 2.04
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4
- [x] a Leading product repository
- [x] repository name must be _productname_ without prefix or suffix
- [x] should contain the release
- [x] references/urls to the product's other repositories
- [x] might contain product helm chart
- [x] README.md: contains the urls for the backend and frontend applications
##### TRG 2.05
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5
- [x] `.tractusx` metafile is present in the root of the repository
- [x] file has a proper format
##### TRG 3.02
https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2
- [x] if data persistence is needed in Kubernetes the use of PersistentVolume and PersistentVolumeClaim resource
##### TRG 4.01
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-1
- [x] All images must be tagged following [semantic versioning](https://semver.org/)
- [x] container is labeled correctly additionally to the latest tag
##### TRG 4.02
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-2
- [x] must add a section to your top level `README.md` file, that contains information about the used base image
- [x] Java, Kotlin, ... if JVM based language use base image from [Eclipse Temurin](https://hub.docker.com/_/eclipse-temurin)
##### TRG 4.03
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-3
- [x] image has `USER` command to specify a non-root user to run the container
- [x] #101
##### TRG 4.05
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-5
- [x] released image must be present on `GitHub Package registry` or `Dockerhub`
##### TRG 5.01
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01
- [x] Helm chart must be released
- [x] appropriate semantic versioning for `version` and `appVersion` has to be used in `Chart.yaml`
- [x] must not contain any environment specific `values-xyz.yaml`
- [x] `values.yaml` file must contain proper default values/placeholders
- [x] No hostname provided for ingress
- [x] Ingress is disabled
- [x] No references to any secret engine service (e.g.: Hashicorp Vault)
- [x] Dependencies should be prefixed with the nameOverride and/or fullnameOverride properties
- [x] Image tag is set to the `Chart.yaml` `appVersion` property
- [x] must be deployable to any environment without overwriting default values with a simple helm install command
- [x] dependencies have to be declared in Chart.yaml NOT requirements.yml
##### TRG 5.02
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02
- [x] Helm chart location inside Git repository in `/charts` directory
- [x] chart file structure
``` markdown
charts/ 
    chartNameA/
      Chart.yaml
      ... 
    chartNameB/
      Chart.yaml
      ...
AUTHORS.md 
DEPENDENCIES.md 
LICENCE 
README.md 
```
- [x] each file must contain the [Apache 2.0 Licence](https://github.com/catenax-ng/foss-example/blob/main/general/LICENSE)
- [x] latest tag is not used in helm chart be default
##### TRG 5.04
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04
- [x] CPU and memory limits and requests are properly set
##### TRG 5.06
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06
- [x] every startup configuration aspect of your application must be configurable through the Helm chart (ingress class, tls, labels, annotations, database, secrets, persistence, env variables)
##### TRG 5.07
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07
- [x] if dependencies are present in the `Chart.yaml` they are properly configured
##### TRG 5.08
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08
- [x] a product has a single deployable helm chart that contains all components (backend, frontend, etc.)
- [x] name of the Chart should be just the product-name without prefix or suffix
- [x] values file should contain all available variables (even from subcharts) with default values and comments about what they do
- [x] helm install command should successfully install the chart to any supported Kubernetes version cluster (without overwriting default values)
- [x] helm test runs without errors

#### Testing
- [x] installed and running on pre-prod without errors

**Comment by almadigabor** [comment]
Hi IRS Team! I would kindly ask you to fill these information:

```
Product Owner:
Dev SPOC:
Helm Chart Version:
App Version:
```

**Comment by ds-jhartmann** [comment]
Hi Gabor, 
I added the information:
```
Product Owner: Johannes.Zahn@bmw.de
Dev SPOC: Jaro.Hartmann@doubleslash.de
Helm Chart Version: 5.0.9
App Version: 2.4.0
```

**Comment by almadigabor** [comment]
#101 issue opened

**Comment by ds-jhartmann** [comment]
Hi @almadigabor ,
https://github.com/eclipse-tractusx/item-relationship-service/issues/101 is fixed and we released a new helm and IRS version.
```
Helm Chart Version: 5.0.10
App Version: 2.4.1
```

**Comment by almadigabor** [comment]
Check done and approved by me.
