### ISSUE TITLE
Running Upload script error

### ISSUE THREAD

**Issue by safdar-shahir** [eclipse-tractusx/item-relationship-service#144]
Hi,
I am trying run the upload test data script. But It seems that running it results in an error.
Error screenshot:
![image](https://github.com/eclipse-tractusx/item-relationship-service/assets/141152701/d36ee427-5493-4b14-88d9-20dfeb066645)
Is there any issue with test data?
Is it any version mismatch issue?

**Comment by ds-jhartmann** [comment]
Hi @safdar-shahir, 
are you trying to upload the data to the full-irs local deployment? In this case the most recent state of main is not working, due to a lot of changes to the EDC- and DigitalTwinRegistry-API recently. 
Try checking out tag `2.6.1`.
Let me know if this could resolve your issue

**Comment by ds-jhartmann** [comment]
Hi @safdar-shahir, 
since there weren't any updates on this issue, I assume your problems could be resolved and this issue can be closed. 
Feel free to reopen it, if you still need help
