### ISSUE TITLE
.helmignore contains environment specific values files

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/item-relationship-service#147]
`.helmignore` should contain the environment specific values files like in this [TRG](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02#helmignore).

**Comment by almadigabor** [comment]
Accepted the QG4 check as the repo does not contain env specific values files but please do this addition to the helmigore as soon as possible.

**Comment by ds-jhartmann** [comment]
Hi @almadigabor this was added as part of https://github.com/eclipse-tractusx/item-relationship-service/pull/156
