### ISSUE TITLE
chore: include FOSS files in the built artifact

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/item-relationship-service#152]
You need to include the license, notice and dependencies file in your artifact (not in docker image, but in .jar this case) according to this [TRG](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05#description). You can take a look at [this example](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/consumer-backend/productpass/pom.xml#L189-L202) that already does the same.

- Also you need to get rid of these file from the docker image or at lease don't include them in the root as it would indicate that all files in the image are under Apache 2.0 license.

**Comment by almadigabor** [comment]
Hi @ds-ext-kmassalski! Looks good, you can open a PR for eclipse repo too.

**Comment by ds-jhartmann** [comment]
Hi @almadigabor, the changes are merged to eclipse-tractusx as part of https://github.com/eclipse-tractusx/item-relationship-service/pull/155 now

**Comment by almadigabor** [comment]
Hi @ds-jhartmann! Thanks, closing the issue.
