### ISSUE TITLE
chore: add Apache 2.0 reference to documentation

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/item-relationship-service#153]
Please add a reference to the Apache 2.0 license to the starting point to each of your documentation (for example Arc42, User Guide, Admin Guide) according to this [TRG](https://eclipse-tractusx.github.io/docs/release/trg-0/trg-7-07#documentation).

**Comment by mkanal** [comment]
@ds-ext-kmassalski provided the link to the PR for approval

**Comment by almadigabor** [comment]
Hi @ds-ext-kmassalski! Yes it looks good, you can open a PR for the eclipse repo too.

**Comment by almadigabor** [comment]
Hi @ds-jhartmann! Thanks, closing this now.
