### ISSUE TITLE
adapt to Github Development Workflow

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#187]

**Comment by FaGru3n** [comment]
Hi should this dedicated task for IRS stay on the Release Planning Bord?

i would remove this from the Board because overaching idea is represented in eclipse-tractux/sig-release in issue 212

**Comment by jzbmw** [comment]
It is not on the Board. 
It is an issue in the item-relationship-service 
I created this with a Feature tasklist option to transfer that into an issue and then moved it in the IRS Repo.

**Comment by FaGru3n** [comment]
I guess this is the problem that by transfering the issue into the dedicated irs-repo the issue link to the board will stay there...
so just for infomation purpose if you plan more feautures 😉 

no problem just also a learning and finding thing to us all... no problem at all 

> [jzbmw](https://github.com/jzbmw) transferred this issue from eclipse-tractusx/sig-release [1 hour ago](https://github.com/eclipse-tractusx/item-relationship-service/issues/187#event-10630531423)

**Comment by jzbmw** [comment]
Maybe it is good to give guidance on that. For me it feels like that other teams will run in this very soon. 
Might be there a possibility to choose the repo in which the issue should be generated?

**Comment by FaGru3n** [comment]
> Maybe it is good to give guidance on that. For me it feels like that other teams will run in this very soon. Might be there a possibility to choose the repo in which the issue should be generated?

in my knowledge area actually not, when using the "convert to issue" on actually generated issue in sig-release only on draft issue on the board itself you can choose in which repository this issue will open but then is also on the planning board where we not want to have it...  

![image](https://github.com/eclipse-tractusx/item-relationship-service/assets/121097161/95c51c9e-358a-4ed8-ae1a-a33dff3905c9)

![image](https://github.com/eclipse-tractusx/item-relationship-service/assets/121097161/0b0c8fe8-f919-4678-9071-a96221126efb)


https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-items-in-your-project/converting-draft-issues-to-issues

**Comment by stephanbcbauer** [comment]
@FaGru3n @jzbmw thx for this discussion ... will take this information and add it to my "Get Ready" presentation (wiki page) for our open planning

**Comment by FaGru3n** [comment]
> @FaGru3n @jzbmw thx for this discussion ... will take this information and add it to my "Get Ready" presentation (wiki page) for our open planning

FYI: https://github.com/eclipse-tractusx/sig-release/discussions/227#discussioncomment-7272724

**Comment by FaGru3n** [comment]
HI @jzbmw i guess we can close this issue for now or should we leave it open for demo purpose?
