### ISSUE TITLE
Building block view adaptions for ESS UseCase in ARC42 Documentation

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#203]
*As* external developer
*I want* the structure of the system visualizes as a Building block view
*so that* I know how the components interact with each other and which interfaces the IRS is providing for the ESS capability

## Hints / Details

- ESS (Environmental and Social Standards)
- BuildingBlock View ARC42 https://eclipse-tractusx.github.io/item-relationship-service/docs/arc42/full.html#_building_block_view
- Swagger API https://irs.int.demo.catena-x.net/api/swagger-ui/index.html?configUrl=/api/api-docs/swagger-config
- ARC42 explaination https://www.dokchess.de/en/

### Outcome
- ...
### Acceptance Criteria
- [x] ESS Capability is documented in the ARC42 Building block view section 
- [x] Whitebox overall system Component diagram + Component diagram description 
- [x] Level 1 Component diagram + Component diagram description
- [x] Level 2 Component diagram + Component diagram description
- [x] IRS API description is extended with endpoints (POST /ess/bpn/investigations | GET /ess/bpn/investigations/{id} |  POST /ess/bpn/investigations/{id})

## Out of Scope

- ...

**Comment by mkanal** [comment]
- [ ] Outcome ist not documented - please provide more evidence 
- [ ] Whitebox overall system is not updated 
- [ ] Table is not updated 
- [ ] Recursice Job handler is not defined - what is the recurisvejobhandler doing seems like this is only an internal topic
- [ ] This is very thin explaination "The RecursiveJobHandler handles the job execution recursively until a given abort criteria is reached or the complete item graph is build." An external contributors will not have any glue what this might mean or how this is done. Recommendation as I mentioned some days ago - separate the different working modes recursive and iterative to give more details how the solution works and which shared services are used and how they are used .

**Comment by ds-jhartmann** [comment]
Whitebox overall view and table related to ESS cases are updated in #206
All other open points pointed out by @mkanal are done or not applicable (see @ds-ext-kmassalski comment)
