### ISSUE TITLE
Runtime view adaptions for ESS UseCase in ARC42 Documentation

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#204]
**As** external developer
**I want** the that the dynamic aspects of the ESS use case is visualizing in the Runtime view
**so that** I know how the components interact with each other and which interfaces the IRS is providing for the ESS capability.

## Hints / Details

- ESS (Environmental and Social Standards)
- Runtime View ARC42 https://eclipse-tractusx.github.io/item-relationship-service/docs/arc42/full.html#_building_block_view
- Swagger API | https://irs.int.demo.catena-x.net/api/swagger-ui/index.html?configUrl=/api/api-docs/swagger-config
- ARC42 explanation https://www.dokchess.de/en/

### Outcome
- [x] Runtime View is adapted to ESS and review was done 
- [x] Runtime View is available on eclipe tractus-X https://eclipse-tractusx.github.io/item-relationship-service/docs/arc42/full.html#_irs_recursive
- [x] Heading is fixed with fix(document):[#204] fix headings of documentation

### Acceptance Criteria
- [x] ESS Capability is documented in the ARC42 Building block view section
- [x] Scenario based runtime views for ESS API Endpoints

## Out of Scope

- ...

**Comment by mkanal** [comment]
PO acceptance on behalf of @jzbmw
