### ISSUE TITLE
[PO_REVIEW] Capability to conduct a "Ready to use" Check/Tests after installation process of IRS

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#205]
**As** a company admin,
**I want** have a ready to use check after installation process,
**so that** I can check if my installation procedure was successful and my work is done.

## Hints / Details

- basic health checks, with the dependencies (Semantic Hub. dDTR, EDC )
   - Health check with indicator (green, yellow or red) / Spring actuator
- Are the dependencies reachable
- log this as normal application logs in level info or warm weather a dependency is available or not

### Outcome
- ...
### Acceptance Criteria
- [x] IRS has a "ready to use" check or tests which evaluates if installation was successful and IRS could be used 
- [x] Provides APIs of Shared Services is checked if reachable and accessible
- [x] Basic health checks, with the dependencies like shared services

## Out of Scope

- ...

##  Sprint Planning 2 

1.  Check for health endpoints of shared services 
2.  Idea: Make a basic call on an endpoint without parameter GET /models and check HTTP Status code 200 
3.  Swagger is reachable 
4. Log the status of shared services in a comprehensible way (if possible)
5. Expose status on actators

**Comment by mkanal** [comment]
@jzbmw 
We should think about a follow-up story to show the health status provided by the spring actuators in Grafana Dashbaord.

**Comment by mkanal** [comment]
PO acceptance by @mkanal during Iteration Review in representation of @jzbmw
