### ISSUE TITLE
[CONCEPT] Update of aspect model SingleLevelBomAsBuilt 2.0.0

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#212]
**As** a User of Trace-X 
**I want** to be able to see the part tree one level up and one level down 
**so that** I can send quality notifications and quality alerts

## Hints / Details

- https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.single_level_bom_as_built/2.0.0
- @jzbmw how to deal with "hasAlternatives"?

### Outcome
- [x] Process on how to deal with the hasAlternatives has been conceptualized
- [x] PR https://github.com/catenax-ng/tx-item-relationship-service/pull/651
- [x] #296 

### Acceptance Criteria
- [x] IRS supports Aspect model  SingleLevelBomAsBuilt V2.0.0 with the hasAlternative property
- [x] Update https://eclipse-tractusx.github.io/item-relationship-service/docs/arc42/full.html Chapters Traversal Aspect & Semantic Model

## Out of Scope

- ...

**Comment by jzbmw** [comment]
Dependency to Trace-X

**Comment by mkanal** [comment]
@jzbmw  Mermaid is now working please review: https://github.com/catenax-ng/tx-item-relationship-service/blob/main/docs/concept/%23212-Update-of-aspect-model-SingleLevelBomAsBuilt-2_0_0/%23212-Update-SingleLevelBomAsBuilt-2-0-0.md
