### ISSUE TITLE
Preparation of IRS LIVE DEMO @ CX ART System Demo PI10

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#217]
As TEAM
I want to live showcase the achievements of PI 10
so that we could demo at glance what we have crafted during PI10

## Hints / Details

- Content for around 15-20minutes
- slides vs. demo (winner) 

### Outcome
- [x] FeaturesList to showcase is prepared >> Alignment for Policy Store and ESS use case 
- [x] We know how and what to DEMO >> We align with the Demo Agenda 
- [x] Agenda and Planning conducted. >>  We align with the Demo Agenda
- [x] Features : Policy Store and ESS Top Down Approach is shown  >> Demo was conducted and https://confluence.catena-x.net/display/IRS/12.+System+Demos
- [x] Slides which shows the purpose and the structure what will be shown are present  >> Slides are here https://confluence.catena-x.net/display/IRS/12.+System+Demos

### Acceptance Criteria
- [x] FeaturesList to showcase is prepared 
- [x] We know how and what to DEMO 
- [x] Agenda and Planning conducted. 
- [x] Features : Policy Store and ESS Top Down Approach is shown 
- [x] Slides which shows the purpose and the structure what will be shown are present 

## Out of Scope

- ...

**Comment by jzbmw** [comment]
@mkanal did the team prepare sth. in my absence last week?

**Comment by jzbmw** [comment]
@mkanal this time im not available to that meeting. Please prepare some Slides of the results of the PI10.

**Comment by mkanal** [comment]
@jzbmw  system demo was conducted. There was a great feedback in PO Sync CXART. Outcome is documented in confluence. I will close this.
