### ISSUE TITLE
Update Data Chain KIT to current version

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#219]
As a possible IRS Consumer,
I want to know all the benefits of the service,
so that I can decide to build my application upon that

## Hints / Details

- https://eclipse-tractusx.github.io/docs-kits/kits/Data%20Chain%20Kit/Adoption%20View%20Data%20Chain%20Kit

### Blocker
[TRI-1554](https://jira.catena-x.net/browse/TRI-1554) (Use Case extension)
#215 (Adoption View extension)

### Outcome
- ...
### Acceptance Criteria
- [ ] Preparation of sketches for Key Visual (SVG, PNG)
- [ ] Update all related chapters
- [ ] Update changelog
- [ ] Update Operation View to current state of development  
- [ ] Update Development View to current state of development 
- [ ] Success stories are moved to Use Case section of adoption view 
- [ ] Documentation is on current version (update uml diagrams , update text, correct incorrect text )
- [ ] KIT has TRG  conformity 
- [ ] Add API Documentation to the tractus-x swagger documentation

## Out of Scope

- ...

**Comment by jzbmw** [comment]
Open to clarify: 
which swagger shall be used for tractus-X

**Comment by ds-jhartmann** [comment]
Updated Data Chain Kit in https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/547
- Development View: Update request collection to latest state of IRS
- Documentation: Update Arc42 and Admin guide to latest state of IRS
- Moved Success Stories to Adoption View
