### ISSUE TITLE
Transfer to Tractus-X Focus topics regarding Post Consortia

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#223]
**As** PO
**I want** to have a clear understanding how we want to proceed and what efforts we have regarding the migration from C-X to Tractus-X
**so that** I am able to plan the transition and prioritize the topics

## Links
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/371
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/312
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/344

## Hints / Details
- child of eclipse-tractusx/sig-release#212
- https://confluence.catena-x.net/display/IRS/%5BPCWM%5D%5BTRI1520%5D+%5BPCWM%5D+%5BCONCEPT%5D+Transfer+to+Tractus-X+Focus+topics+regarding+Post+Consortia

- [x] Concept how Planning is conducted in GitHub 
- [x] Concept how to replace Confluence 
- [x] Concept how to replace JIRA
- [x] Concept covers: 
  - [x] How to migrate the Confluence pages to GitHub (Pages, Wiki, MD, issues)
  - [x] How to migrate the JIRA pages to GitHub (Pages, Wiki, MD, issues)
  - [x] Transition from Jira to GitHub Projects
  - [x] Testmanagement and Test Reporting (Xray)
  - [x] CATENAX-NG environment 
  - [x] Change of development workflow
  - [x] Vision and Mission Statement of repository
  - [x] How to conduct the PIP Planning in Tractus-X 

### Outcome
- [x] Backlog Items generated
- [x] Migration concept and migration steps are documented
- [x] Vision and Mission Statement of repository>> https://github.com/eclipse-tractusx/item-relationship-service/wiki
- [x] Concept how to replace JIRA >>  

### Acceptance Criteria
- [x] Backlog Items have been generated for all necessary steps
- [x] The Concept has been finalized
- [x] Migration steps / order has been documented

## Out of Scope

-

**Comment by ds-jhartmann** [comment]
created first draft of concept in https://github.com/catenax-ng/tx-item-relationship-service/pull/701
@jzbmw could you please give feedback on this?

**Comment by jzbmw** [comment]
@ds-jhartmann I've read the doc. 
I think only small parts of our Confluence is necessary to transfer. So for that a copy paste is also possible. 

For the Testmanagment topic, I like the Github Action to show test results.

About the environments we will see what the overall plan will be. But for now it fits to the current requirements

**Comment by mkanal** [comment]
@ds-jhartmann 
Confluence - I would not recommend moving Confluence pages automatically. 
# We should mark which content is related 
#

**Comment by ds-jhartmann** [comment]
@jzbmw @mkanal I added your remarks to the PR. Feel free to give your approval, if you are satisfied with the concept.

**Comment by mkanal** [comment]
Hi @jzbmw 
this ticket is ready for PO review. Thank you very much.

**Comment by ds-jhartmann** [comment]
Issues for implementation:
https://github.com/eclipse-tractusx/item-relationship-service/issues/371
https://github.com/eclipse-tractusx/item-relationship-service/issues/312
https://github.com/eclipse-tractusx/item-relationship-service/issues/344
