### ISSUE TITLE
[PO_REVIEW] Create workflow to check for CHANGELOG updates

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#224]
**As** ... ,
**I want** ... ,
**so that** ... .

## Hints / Details

- Idea: Create a workflow that checks whether the CHANGELOG file has been updated in a PR.

Since not every commit adds something that needs to be reflected in the CHANGELOG, there could be some conditions in the trigger:
 * Only run on changes to Java files or POMs
 * Only run on feature / fix branches
 * ...?

The workflow could fail, if no CHANGELOG update was detected. Alternatively, it could write a comment to the PR, to remind the developer.

### Outcome
- ...
### Acceptance Criteria
- [ ] ...

## Out of Scope

- ...

**Comment by mkanal** [comment]
PO acceptance by @mkanal during Iteration Review in representation of @jzbmw
