### ISSUE TITLE
Use caching for Discovery Finder requests for performance reasons

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#225]
**As** Developers
**I want**
**so that** 

## Hints / Details

- link to Thomas Henn

### Outcome
- ...
### Acceptance Criteria
- [ ] Responses of Discovery Finder Service is cached 
- [ ] Cache uses ttl for cached responses 
- [ ] Default TTL is 1 day
- [ ] TTL could be configured via IRS config (App Configuration + Helm Charts)
- [ ] Admin manual covers required information about cache and cache settings 
- [ ] ARC42 is extended 

## Out of Scope

- ...

**Comment by mkanal** [comment]
@jzbmw  Please let us develop a User Story on friday

**Comment by ds-jhartmann** [comment]
## Planning 2
- see description of #210 for more information regarding the workflow

**Comment by dsmf** [comment]
**Outcome:**
- [x] provider method for DiscoveryFinderClient has been added to RegistryConfiguration to enable the use of Spring annotations in DiscoveryFinderClient 
-  [x] DiscoveryFinderClientImpl.findDiscoveryEndpoints is cached
-  [ ] Default TTL is 1 day
-  [ ] TTL can be configured via IRS config (App Configuration + Helm Charts)
-  [ ] Admin manual covers required information about cache and cache settings
-  [ ] ARC42 is extended

**Comment by dsmf** [comment]
Hi @ds-jhartmann, as discussed I updated the ARC42 documentation. Could you have a look at it, please?
