### ISSUE TITLE
⭐[QG][QG4][RELEASE_23.12] IRS Release 23.12 - Application Security Testing

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#237]
**As** ... ,
**I want** ... ,
**so that** ... .

## Hints / Details

- ...

### Outcome
- ...
### Acceptance Criteria
* (x) PEN Test environment is updated with release 23.12 4.0.0_RC_1
* (x) Static Application Security Testing (SAST) no findings with severity higher than medium
* (x)  Dynamic Application Security Testing (DAST) no findings with severity higher than medium
* (x) Secret scanning no findings 
* (x)  Software Composition Analysis (SCA)   no findings with severity higher than medium
* (x) Container Scan conducted no findings with severity higher than medium
* (x) Infrastructure as Code IaC code must be scanned.

# Hint 
Static Application Security Testing (SAST)
https://github.com/eclipse-tractusx/sig-release/issues/86

Dynamic Application Security Testing (DAST)
https://github.com/eclipse-tractusx/sig-release/issues/86
Secret scanning
https://github.com/eclipse-tractusx/sig-release/issues/86

Software Composition Analysis (SCA)
https://github.com/eclipse-tractusx/sig-release/issues/86

Container Scan conducted
https://github.com/eclipse-tractusx/sig-release/issues/86

Infrastructure as Code
IaC code must be scanned.

https://github.com/eclipse-tractusx/sig-release/issues/86

## Out of Scope

- ...

**Comment by jzbmw** [comment]
we already got our QG
