### ISSUE TITLE
Update EDC to version 0.5.1

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#238]
**As** team
**I want** to be aligned with the latest version of EDC 
**so that** interoperability to other products like SDE is given. 

## Hints / Details

- ...

### Outcome
- ...
### Acceptance Criteria
- (x) EDC dependency is updated in application 
- (x) EDC dependency is updated in helm chart deployment 
- (x) EDC dependency is updated in infrastructure used for testing
 

## Out of Scope

- ...

**Comment by mkanal** [comment]
Please close the story.

**Comment by ds-jhartmann** [comment]
Done in #262
