### ISSUE TITLE
Refactor API Documentation to not contain duplicated values in arrays

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#241]
As Developer,
I want to be able to understand the API and don't have duplicated values in arrays
so that it is clear what to implement.

## Hints / Details

- Example values shall not be shown 5 times
- https://catenax-ng.github.io/tx-item-relationship-service/docs/api-specification/api-specification.html 
- To prevent this from happening example data should be added at higher struct level (mock the array not items themselves). This also require refactoring of open-api annotations on controllers levels. 
- Bad Example: 
```
"subjectId" : {
        "keys" : [ {
          "type" : "urn:bamm:com.catenax.vehicle:0.1.1",
          "value" : "Submodel"
        }, {
          "type" : "urn:bamm:com.catenax.vehicle:0.1.1",
          "value" : "Submodel"
        }, {
          "type" : "urn:bamm:com.catenax.vehicle:0.1.1",
          "value" : "Submodel"
        }, {
          "type" : "urn:bamm:com.catenax.vehicle:0.1.1",
          "value" : "Submodel"
        }, {
          "type" : "urn:bamm:com.catenax.vehicle:0.1.1",
          "value" : "Submodel"
        } ],
        "type" : "type"
      } 
```

Feature: 
- eclipse-tractusx/sig-release#450

### Acceptance Criteria
- [x] Correct OpenApi documentation in product documentation 

## Out of Scope

- ...

**Comment by ds-psosnowski** [comment]
PR: https://github.com/catenax-ng/tx-item-relationship-service/pull/813

**Comment by ds-psosnowski** [comment]
@mkanal story is ready for review
docs can be found here: https://catenax-ng.github.io/tx-item-relationship-service/docs/api-specification/api-specification.html

**Comment by mkanal** [comment]
![image](https://github.com/eclipse-tractusx/item-relationship-service/assets/100209308/f9e26985-e75b-44d9-a830-d9db3cd59822)
