### ISSUE TITLE
Check if SingleLevelBomAsBuilt is fixed in SemanticHub

### ISSUE THREAD

**Issue by ds-alexander-bulgakov** [eclipse-tractusx/item-relationship-service#242]
**As** user,
**I want** aspect SingleLevelBomAsBuilt to be fixed,
**so that** i can request IRS-jobs with this aspect successfully.

## Hints / Details
- SLBAB is existing in Semantic-Github 
- SLBAB version 1.0.0 is still valid and in github repo
- SLBAB in version 2.0.0 is buggy, fix is planed for PI11
- In current testdataset SLBAB is present in version 2.0.0

### Outcome
- 
### Acceptance Criteria
- SLBAB can be requested successfully for version 1.0.0 and 2.0.0.

## Out of Scope
-

**Comment by jzbmw** [comment]
until resolvement by semantic hub we accept that behaviour.

**Comment by jzbmw** [comment]
https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.single_level_bom_as_built/2.0.0 Seems to be ready

**Comment by ds-alexander-bulgakov** [comment]
@jzbmw the version 2.0.0 is still missing in the SemanticHub which is actually the issue, therefore we still can not request SLBAB models. Only the 1.0.0 version is released yet.
