### ISSUE TITLE
[ESS][SUPPLY-CHAIN_ACT] IRS ESS shows infected Supply-Chain on 1.(first) Tier Level

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#244]
**As** user
**I want** that the sub-tree where infection was found is known
**so that** I am able to address the correct supplier for more investigation

## Hints / Details

- https://confluence.catena-x.net/display/IRS/%5BTRI-1519%5D%5BTRI-1523%5D+IRS%3A+ESS+Top-Down+Use+Case

![Image](https://github.com/eclipse-tractusx/item-relationship-service/assets/48311334/f82614b7-8b4f-49ef-b06f-bd387bd027a4)

### Outcome
- ...
### Acceptance Criteria
- [x]  ESS Job Response contains the sub-tree on first Tier level where infection was found
- [x] The BPNL of Tier 1 Supplier is passed as impactedSupplierOnFirstTier. 
- [x] Final aggregation contains infected supply chain  BPNL on first Tier level.  

## Out of Scope

- ...

**Comment by ds-alexander-bulgakov** [comment]
FYI I corrected the ESS testdatafile ESS_Testdata_v2.0.0-AsPlanned.json since the "Vehicle D" ids were not completely correct. Changes pushed to Pawels branch feature/TRI-1658-infected-supply-chain-on-first-tier-level.
Please note the changes are not uploaded yet.

**Comment by ds-alexander-bulgakov** [comment]
Hi @ds-psosnowski!
I was able to detect an issue for requests on first incident level. See e.g. request 
`{
    "key": { "globalAssetId": "urn:uuid:3a2a1ca9-c6c1-49c7-a7ae-1dfc5fb9881f", "bpn": "BPNL00ARBITRARY8" },
    "incidentBPNSs": ["BPNS0ARBITRARY10"],
    "bomLifecycle": "asPlanned"
}`
which is expected to have the "bpnl" result "BPNS0ARBITRARY10" but is "BPNL00000004FAIL" instead:
<img width="621" alt="MicrosoftTeams-image" src="https://github.com/eclipse-tractusx/item-relationship-service/assets/114988128/a60b3968-5f10-4b4e-aa69-183b2d247994">
Could you have a look please?

**Comment by ds-alexander-bulgakov** [comment]
Please also have a look on scenario with more then one node with affected BPN. E. for this request:
`{
    "key": { "globalAssetId": "urn:uuid:aad27ddb-43aa-4e42-98c2-01e529ef127c", "bpn": "BPNL00ARBITRARY1" },
    "incidentBPNSs": ["BPNS00000003B6LU"],
    "bomLifecycle": "asPlanned"
}`
<img width="604" alt="image" src="https://github.com/eclipse-tractusx/item-relationship-service/assets/114988128/f26b3150-c465-4b36-9207-9cc1f081c6d7">

we are expecting two entries in the impactedSuppliersOnFirstTier array. Currently there is only one.

**Comment by ds-alexander-bulgakov** [comment]
No more issues could be found during testing on ESS-INT with branch _feature/TRI-1658-infected-supply-chain-on-first-tier-level_. The first tier level with infection is detected correctly, see e.g. request:
`{
    "key": { "globalAssetId": "urn:uuid:3a2a1ca9-c6c1-49c7-a7ae-1dfc5fb9881f", "bpn": "BPNL00ARBITRARY8" },
    "incidentBPNSs": ["BPNS0ARBITRARY11"],
    "bomLifecycle": "asPlanned"
}`
and _impactedSupplierOnFirstTier_ result:
`"submodels": [
		{
	"identification": null,
	"aspectType": "supply_chain_impacted",
	"payload": {
		"supplyChainImpacted": "Yes",
		"impactedSuppliersOnFirstTier": {
			"bpnl": "BPNL00ARBITRARY10",
			"hops": 2
     }...`
Tavern tests have been added to same branch. This is the outcome:
- ESS Job Response contains the sub-tree on first Tier level where infection was found.
- The BPNL of Tier 1 Supplier is passed as impactedSupplierOnFirstTier.
- Tavern tests have been implemented. See JIRA tickets TRI-1757, TRI-1758, TRI-1759 and TRI-1760.

Ticket is ready for PO-review.
