### ISSUE TITLE
Alignment with BOMSpec Team providing mandatory businessPartner in SingleLevel* structure

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#245]
**As** IRS Team
**I want** a solution how to deal with missing BPN number in traversal aspects 
**so that** we are able to traverse through the value chain 

## Hints / Details
- Get in Contact with [Nicole Kauke](https://jira.catena-x.net/secure/ViewProfile.jspa?name=Nicole.KA.Kauke%40bmw.de) how to proceed on this topic

## Outcome / Acceptance Criteria

- [ ]  Aligment with BOMTeamSpec team for an additional attribute in SingleLevel* structure
- [ ]  All necessary steps (Release Process, Testdata Management, Update Semantic Models in IRS ) are aligned
- [ ]  Alignment with BOMSpec Team

### Outcome
- ...
### Acceptance Criteria
- ...

## Out of Scope

- ...

# 2024-03-13

| Aspect | Version | BusinessPatner Number |  Mandatoy |
|---|---|---|---|
| SLBAB | 3.0.0  | Y  | Y |
| SLBAP | 3.0.0  | Y  | Y |
| SLUAB | 3.0.0 | Y | Y |
| SLUAP | 3.0.0   | Y  | Y |

# 2023-11-30

| Aspect | Version | BusinessPatner Number |  Mandatoy |
|---|---|---|---|
| SLBAB | 2.0.0  | Y  | Y |
| SLBAP | 2.0.0  | Y  | Y |
| SLUAB | 2.0.0 | N  | N |
| SLUAP | 1.1.0   | N  | N |

# 2024-02-02

| Aspect | Version | BusinessPatner Number |  Mandatoy |
|---|---|---|---|
| SLBAB | 2.0.0  | Y  | Y |
| SLBAP | 2.0.0  | Y  | Y |
| SLUAB | 2.0.0 | Y  | Y |
| SLUAP | 1.1.0   | N  | N |

##  Requirement Originator
 * Requirement of Trace-X

## Progress:
 * Further alignment BMW Sync tomorrow 3.8.2023 [~steffen.duering@bmw.de] & [~Nicole.KA.Kauke@bmw.de] & [~Markus.Keidl@bmw.de]
 * Alignment with policy experts [~malte.hellmeier@isst.fraunhofer.de] and [~Matthias.Binzer@de.bosch.com]
 *

**Comment by jzbmw** [comment]
@mkanal I dont understand yet the topics mentioned here. I need some update on this

**Comment by jzbmw** [comment]
mail an semantic modelling team has been sent on 30th november. Waiting for response
