### ISSUE TITLE
[ESS][SUPPLY-CHAIN_ACT][TOP DOWN APPROACH] Return the number of hops (relative distance in the supply chain) to an event from the requester's perspective.

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#246]
USE THIS AS REFERENCE
https://jira.catena-x.net/browse/TRI-1641

- child of eclipse-tractusx/sig-release#213

**Comment by ds-alexander-bulgakov** [comment]
During QA-review on branch TRI-1658-infected-supply-chain-on-first-tier-level hops could not be reproduced as expected. The number is always "1". See e.g. request for "Vehicle A" from testdataset ESS 2.0.0 which should be response with "hops = 4":
`"submodels": [
		{
			"identification": null,
			"aspectType": "supply_chain_impacted",
			"payload": {
				"supplyChainImpacted": "Yes",
				"impactedSuppliersOnFirstTier": [
					{
						"bpnl": "BPNL00ARBITRARY1",
						"hops": 1
					}
				]
			}
		}
	]`
@ds-ext-kmassalski could you please have a look once again?

**Comment by ds-alexander-bulgakov** [comment]
No more issues could be found during QA-review. _hops_ are detected correct now. See example for request
`{
    "key": { "globalAssetId": "urn:uuid:0733946c-59c6-41ae-9570-cb43a6e4c79e", "bpn": "BPNL00000003AYRE" },
    "incidentBPNSs": ["BPNS00000003B6LU"],
    "bomLifecycle": "asPlanned"
}`
with response and shortest node:
`"submodels": [
		{
			"identification": null,
			"aspectType": "supply_chain_impacted",
			"payload": {
				"supplyChainImpacted": "Yes",
				"impactedSuppliersOnFirstTier": {
					"bpnl": "BPNL00ARBITRARY1",
					"hops": 2
				}`
<img width="559" alt="image" src="https://github.com/eclipse-tractusx/item-relationship-service/assets/114988128/311c922c-8ff9-4ee1-bdb8-65f5143e6d03">


See outcome:
* Requestor gets the number of hops which are in between the incident and himself in the supply chain.
* Hops of shortest path is detected correctly for cases with several nodes with infected parts.
* Tavern tests have been implemented. See JIRA tickets TRI-1761, TRI-1762, TRI-1763.

Ticket is ready for PO-review.
