### ISSUE TITLE
Extend the structure of how the IRS can handle Policies

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#249]
**As** IRS Consumer,
**I want** to add policies the same way as EDC handles those ,
**so that** there is no structural change within the overall architecture of where the Services acts.

## LOP 
* @jzbmw  should we use json-ld as the EDC uses that. This might increase the complexity. Odrl: Prefix would not be used if we do not use json-ld . Alternative, we could use the term  odrl:action as a string attribute and ignoring the namespace :odrl 

## Hints / Details
- child of eclipse-tractusx/sig-release#212
- policy store concept https://confluence.catena-x.net/display/IRS/%5BTRI-1320%5D%5BTRI-1512%5D+IRS%3A+PolicyStore

Example: 
```json
{
	info: xy,
	ttl: xx,
	policy_use_for_use_case:[xys,ggg,ggg,]
	payload  {
		...policy payload... as it is  
	}
}

```

Example: 

```json
{
  "@context": {
      "odrl": http://www.w3.org/ns/odrl/2/
  },
  "@type": "PolicyDefinitionRequestDto",
  "@id": "ap-bpn-and-up-member-trace-idtrace-up",
  "policy": {
      "@type": "Policy",
      "odrl:permission": [
          {
              "odrl:action": "USE",
              "odrl:constraint": {
                  "@type": "LogicalConstraint",
                  "odrl:and": [
                      {
                          "@type": "Constraint",
                          "odrl:leftOperand": "Membership",
                          "odrl:operator": {
                              "@id": "odrl:eq"
                          },
                          "odrl:rightOperand": "active"
                      },
                      {
                          "@type": "Constraint",
                          "odrl:leftOperand": "FrameworkAgreement.traceability",
                          "odrl:operator": {
                              "@id": "odrl:eq"
                          },
                         "odrl:rightOperand": "active"
                      },
                      {
                          "@type": "Constraint",
                          "odrl:leftOperand": "PURPOSE",
                          "odrl:operator": {
                             "@id": "odrl:eq"
                          },
                          "odrl:rightOperand": "ID 3.1 Trace"
                      }
                  ]
              }
          }
      ]
  }
} 
```

### Outcome
- ...
### Acceptance Criteria
- [ ]  EDC policy schema is used for importing policies into Policy store 
- [ ]  it shall be additionally possible to add a policy in the schema described above

## Out of Scope

- ...

**Comment by jzbmw** [comment]
built uppon json-ld

**Comment by ds-psosnowski** [comment]
@ds-alexander-bulgakov ready for QA

**Comment by ds-alexander-bulgakov** [comment]
@ds-psosnowski as already discussed could you please adjust the insomnia-collection with new JSON-body? Thank you!

**Comment by ds-alexander-bulgakov** [comment]
Insomnia collection has been extended and previously described issue with missing _createdOn_ has been fixed, see e.g.:
<img width="423" alt="image" src="https://github.com/eclipse-tractusx/item-relationship-service/assets/114988128/87a7df66-1c8a-4c09-a174-78485579ce49">
Ticket is done and was accepted in PO-review already.
