### ISSUE TITLE
Clear and comprehensible release management documentation and documentation of hotfix path

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#265]
**As** PO
**I want** to have a comprehensible overview which IRS versions belong to which release and the defined version of shared services 
**so that** exactly report which version is in which C-X release and which dependencies we have. 

## Hints / Details

- ...

### Outcome
- ...
### Acceptance Criteria
- Transparent and open documentation of C-X releases and belonging versions
- Each version is linked to the current C-X release 
- For each IRS version the tractusx-edc, sldt-digital-twin-registry,sldt-discovery-finder,sldt-semantic-hub,managed-identity-wallet is documented 
- - See https://github.com/catenax-ng/tx-traceability-foss/pull/710/files for compatibility matrix 

## Out of Scope

- ...

## Mock 

# RELEASE 

### **(Release)** [4.0.0](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.0.0) | [Release Notes](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.0.0)  

| Name of service                  | Version | Comments   |
|----------------------------------|---------|------------|
| postgresql                       | 12.1.6  |            |
| postgresql alias: edc-postgresql | 12.1.6  |            |
| pgadmin4                         | 1.13.6  |            |
| irs-helm                         | 6.8.0   |            |
| tractusx-connector               | 0.5.0   |            |
| discovery service                | 0.1.0   |            |
| portal                           | ?       |            |
| SD-Factory                       | ?       |            |
| wallet                           | ?       |            |

### **(Hotfix)** [4.0.1](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.0.1) | [Release Notes](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.0.1)  

| Name of service                  | Version | Comments   |
|----------------------------------|---------|------------|
| postgresql                       | 12.1.6  |            |
| postgresql alias: edc-postgresql | 12.1.6  |            |
| pgadmin4                         | 1.13.6  |            |
| irs-helm                         | 6.8.0   |            |
| tractusx-connector               | 0.5.0   |            |
| discovery service                | 0.1.0   |            |
| portal                           | ?       |            |
| SD-Factory                       | ?       |            |
| wallet                           | ?       |            |

### **(Hotfix)** [4.0.2](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.0.2) | [Release Notes](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.0.2)  

| Name of service                  | Version | Comments   |
|----------------------------------|---------|------------|
| postgresql                       | 12.1.6  |            |
| postgresql alias: edc-postgresql | 12.1.6  |            |
| pgadmin4                         | 1.13.6  |            |
| irs-helm                         | 6.8.0   |            |
| tractusx-connector               | 0.5.0   |            |
| discovery service                | 0.1.0   |            |
| portal                           | ?       |            |
| SD-Factory                       | ?       |            |
| wallet                           | ?       |            |

### **(Hotfix)** [5.0.0](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/5.0.0) | [Release Notes](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/5.0.0)  

..... 

### **(Hotfix)** [5.0.1](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/5.0.1) | [Release Notes](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/5.0.1)  

..... 

## Dependencies
| Shared Service  | Link                                                                                         |  
|--|----------------------------------------------------------------------------------------------|
|tractusx-edc | [tractusx-edc](https://github.com/eclipse-tractusx/tractusx-edc)                                         | 
|sldt-digital-twin-registry| [sldt-digital-twin-registry](https://github.com/eclipse-tractusx/sldt-digital-twin-registry) |
|sldt-discovery-finder| [sldt-discovery-finder](https://github.com/eclipse-tractusx/sldt-discovery-finder)           | 
|sldt-semantic-hub | [sldt-semantic-hub](https://github.com/eclipse-tractusx/sldt-semantic-hub)                   |
|managed-identity-wallet | [managed-identity-wallet](https://github.com/eclipse-tractusx/managed-identity-wallet)       |

**Comment by mkanal** [comment]
# RELEASE 

## Release 23.9
| Release | Release Notes | Helm Charts | tractusx-edc | sldt-digital-twin-registry | sldt-discovery-finder  | sldt-semantic-hub | managed-identity-wallet| 
|--|--|--------------------------|------------------------|--|--|--|--|
| | |                          |                        | | | |
| | |                          |                        | | | |
| | |                          |                        | | | | 
| | |                          |                        | | | |





## Release 23.12

| Release | Release Notes |  Helm Charts | tractusx-edc | sldt-digital-twin-registry | sldt-discovery-finder  | sldt-semantic-hub | managed-identity-wallet| 
|--|-------------------|--|------------------------|--|--|--|--|
| [4.0.0](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.0.0) | [Release Notes](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.0.0) | |

## Dependencies
| Shared Service  | Link                                                                                         |  
|--|----------------------------------------------------------------------------------------------|
|tractusx-edc | [tractusx-edc](https://github.com/eclipse-tractusx/tractusx-edc)                                         | 
|sldt-digital-twin-registry| [sldt-digital-twin-registry](https://github.com/eclipse-tractusx/sldt-digital-twin-registry) |
|sldt-discovery-finder| [sldt-discovery-finder](https://github.com/eclipse-tractusx/sldt-discovery-finder)           | 
|sldt-semantic-hub | [sldt-semantic-hub](https://github.com/eclipse-tractusx/sldt-semantic-hub)                   |
|managed-identity-wallet | [managed-identity-wallet](https://github.com/eclipse-tractusx/managed-identity-wallet)       |

**Comment by mkanal** [comment]
Hey @ds-jhartmann  kindly ask for your feedback.

**Comment by jzbmw** [comment]
You guys know this discussions? https://github.com/eclipse-tractusx/sig-infra/discussions/373
