### ISSUE TITLE
Condition based automatic E2E testing using dynamic data approach

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#266]
**As** team
**I want** to deal with dynamic data in e2e testing approach 
**so that** I do not have to align on static testdata with multiple providers 

## Hints / Details
- child of eclipse-tractusx/sig-release#217

### Outcome
- ...
### Acceptance Criteria
- [ ] Concept how to deal with dynamic data in a E2E testing approach 

### Hints 
- Concept for Tests scenario implementation requests for all AAS shells for a preconfigured dtr to be tested. (DTR are known in advance ) E2E test scenario could use multiple DTR registry to be tested.  
-  Concept for performance and duration issues the amount of AAS data used for testing could be configured for a specific environment (DEV, INT, STABLE, etc)
- Each AAS shell and the corresponding IRSJob is tested against a set of test scenarios (ESS, IRS up, IRS down) which contains a predefined set of constraints and conditions which ensures the quality and the correctness of IRS job and IRS JobResponses without knowing the concrete structure of the job. 
- Basis set of constraints are defined and implemented in cucumber tests and could be extended later on. 
- For special use cases ESS where we expect an incident we use a pre known BPNS which is configurable within the test scenario   

### Basis Idea behind Conditions 
_The conditions reflect the basic process behind this. We defined condition instead of checking. 

#### Error handling 
- Conditions 1.1: Specific Tombstone creation error condition - Tombstone reflects the error condition 
- Conditions  1.2: Exact one Tombstone for each error
### Relation
- Conditions 2.1: For each relation, there is a corresponding shell 
- Conditions 2.2: In case collect submodels is activated, there is a relationship for each 
- Conditions 2.3: No tombstones - there are no open edges (SingleLevel***)
## Submodels
- Conditions 3.0 - Submodels contains 
## Hops Count 
- Conditions  4.0: Hops reflect the number of hops inside the network 

## Out of Scope

- ...

**Comment by ds-alexander-bulgakov** [comment]
Concept will be done in [[#266] IRS testing using dynamic data](https://confluence.catena-x.net/pages/viewpage.action?pageId=114069433) after the described questions are solved.

**Comment by ds-alexander-bulgakov** [comment]
Concept moved to git concept folder and will be continued there.

**Comment by ds-alexander-bulgakov** [comment]
The concent is ready for review, please see [here](https://github.com/catenax-ng/tx-item-relationship-service/blob/docu/%23266-concept-IRS-testing-with-dynamic-data/docs/concept/%23266-IRS-testing-with-dynamicData/%23266-IRS-testing-with-dynamic-data.md). FYI @jzbmw.

**Comment by jzbmw** [comment]
@ds-alexander-bulgakov I would like to have some discussion about that in the PL. There is some tops I don't understand.

**Comment by ds-alexander-bulgakov** [comment]
@jzbmw i updated the concept after meeting with Varela and Max, it´s ready for your review. Please see [PR #756](https://github.com/catenax-ng/tx-item-relationship-service/pull/756).
