### ISSUE TITLE
Create any kind of notification if dependent applications are broken

### ISSUE THREAD

**Issue by ds-alexander-bulgakov** [eclipse-tractusx/item-relationship-service#268]
**As** IRS user,
**I want** to get notified if dependent applications for IRS have issues,
**so that** i know if the results of the IRS can be unexpected.

## Hints / Details
- As an example the submodel servers restart several times per month. Therefore IRS requests run without submodels in result and the testdata has to be uploaded to the desired environment. There is no notification about the restart and it is necessary to check the logs of submodel servers to make sure this was the issue.

- after Start of a submodel server testdata is beeing loaded automatically.

### Acceptance Criteria
- If submodel server restarted test data has been updated/ uploaded on startup
- ...

## Out of Scope
- ...

**Comment by jzbmw** [comment]
@ds-alexander-bulgakov I need some more information regarding this issue. 
Which submodelservers?
What kind of notification are we talking about?

**Comment by ds-alexander-bulgakov** [comment]
Could probably be discussed or combined in #412.

**Comment by mkanal** [comment]
We close the ticket as we propose status information over Grafana
