### ISSUE TITLE
Visualization of health metrics in Grafana Dashboard

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#283]
**As** Administrator
**I want** a visualization of IRS ready to use health check in Grafana 
**so that** I can see at a glance whether the IRS is ready for operation and can be used. 

## Hints / Details

- ...

### Outcome
- ...
### Acceptance Criteria
- [ ] Health Actuators of shared services are shown in Grafana Dashboard System Health 
- [ ] Health Actuators of IRS are shown in Grafana Dashboard System Health 
- [ ]  Extend HelmCharts dashboard Import Dashboard during setup of application  

## Out of Scope

- ...

**Comment by dsmf** [comment]
![grafik](https://github.com/eclipse-tractusx/item-relationship-service/assets/19529362/4070b9c0-a1dd-4ae6-9b51-7354e3b7a2ed)

**Comment by dsmf** [comment]
- [ ] need to clarify how dashboard is imported
- [ ] rollout on DEV
