### ISSUE TITLE
Building Block Level 2 is missing for Policy Store

### ISSUE THREAD

**Issue by ds-ext-kmassalski** [eclipse-tractusx/item-relationship-service#287]
https://catenax-ng.github.io/tx-item-relationship-service/docs/arc42/full.html#_level_2

Policy Store is not documented in Level 2 Building Block view, but it its mentioned in Level 1.

Feature: 
- eclipse-tractusx/sig-release#450

# Acceptance Criteria 
- [x] Add Building Block View Level 2 to ARC42 documentation for the policy store  

# PR 
- https://github.com/catenax-ng/tx-item-relationship-service/pull/815

**Comment by mkanal** [comment]
@ds-jhartmann @ds-ext-kmassalski kindly ask for a review 
https://github.com/catenax-ng/tx-item-relationship-service/pull/815

**Comment by mkanal** [comment]
@jzbmw  Level two contains missing building block view now in documentation. Kindly ask for PO approval. https://catenax-ng.github.io/tx-item-relationship-service/docs/arc42/full.html#_level_2
