### ISSUE TITLE
TRG 4.02 top level `README.md` file, that contains information about the used base image

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/item-relationship-service#294]
Please get rid of this [line](https://github.com/eclipse-tractusx/item-relationship-service/blob/main/Dockerfile#L54) in your Dockerfile. It is not allowed to modify the base docker image with upgrading packages as we rely on DockerHub scan findings and changing dependencies in it would invalidate the scan results. Even though there might be a Trivy finding, you need to wait for a fixed/new base image and until then release with the findings. You can read more [here](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02#description).

https://github.com/eclipse-tractusx/item-relationship-service/blob/9f39b0dec2586423873d53081db3e1bfc9f0c529/Dockerfile#L54

**Comment by ds-jhartmann** [comment]
Thanks for the hint. We removed the line from the Dockerfile and released it as IRS [4.0.2](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.0.2) and [irs-helm-6.9.2](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/irs-helm-6.9.2)
