### ISSUE TITLE
Add COMPATIBILITY_MATRIX for release documentation

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#297]
**As** Devloper, IRS User, Ops,
**I want** to know with which services the IRS is working properly together,
**so that** some versions change we know exactly where to look.

## Hints / Details
- https://github.com/catenax-ng/tx-traceability-foss/blob/main/COMPATIBILITY_MATRIX.md
- For each IRS-Release

## Acceptance Criteria

- [x] Add a compatibility matrix as changelog in a separate file per Version
- [x] Add Versions as VersionRanges
- [x] Only Versions, which are being used within this sprint.
- [ ] Add this manual process to the release guidlines / steps
- [x] The COMPATIBILITY_MATRIX covers: 
   - [x] EDC version 
   - [x] Semantic Hub Version 
   - [x] MIW Version 
   - [x] Portal Version  
   - [x] dDTR Version 
   - [x] EDC Client library 
   - [x] PostgresSQL
   - [x] Minio 
   - [x] Semantic Models ( relation types ) 
 - [ ] lAYOUT LINKE changelog.md 

## Out of Scope

- ...

**Comment by jzbmw** [comment]
@mkanal Why is it designed in Trace-X as a separate file? Would it not be better to have that in the Release Notes for each Version?

**Comment by ds-jhartmann** [comment]
Planning 2:
- old releases are out of scope. We start with IRS 4.1.0

**Comment by jzbmw** [comment]
change column name to what we discussed in the daily
