### ISSUE TITLE
tractus-x irs local deployment for OpenSource development and testing

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#312]
**As** Open Source Developer ,
**I want** to contribute to test the application,
**so that** I am able to contribute to the project.

## Link 
- relates to - relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/223
- child of - eclipse-tractusx/sig-release#418

## Hints / Details

- the whole setup is for testing purposes, for enabling cx-consorita external partners to develop, test, the scope of the project
- Based on this also within development testing shall be able
- Keep it updated on each release!
- Integrate as much as possible and mock as least as necessary
- **FOCUS:independent of Consortia Resources, but still usable for valid testing**
- Make sure System Team supports as much as possible
- Think about to cases where this is being used testing the development for Consortia outsiders and fulblown setup of all the services
- https://github.com/eclipse-tractusx/e2e-testing/tree/main

 ## Dependencies to clarify
 - Oauth Provider ( Keycloack with settings)
 - MIW with configuration of credentials
 - Semantic Hub API ( with Models )
 - EDC Consumer 
 - Discovery Service
 - Registry
 - EDC Provider
 - Submodel Service
 - Testdata

## Acceptance Criteria
- [ ] develop Strategy how to evolve already existing local deployment
- [ ] develop Strategy how to deal with Dependencies
- [ ] IRS is integrated within the working umbrella helm chart ( as best we can integrate us, dont overjudge the dependencies
- [ ] prepare IRS for easy testing for other teams
- [ ] prepare IRS-Test helm-chart with minimized dependencies
- [ ] Update documentation on Data Chain KIT
- [ ] Update documentation on IRS Documentation
- [ ] List of dependencies which might me stubbed
- [ ] Participate in the initiative to work on the umbrella helm chart

## Out of Scope

- no actual tests to implement this is done in #226

**Comment by jzbmw** [comment]
Wait until #259 is done

**Comment by jzbmw** [comment]
Dependencies are to be maintained on Catena-X Releases.

**Comment by ds-jhartmann** [comment]
Planning 2:
- Use https://github.com/eclipse-tractusx/e2e-testing/tree/main/charts/umbrella for portal and iam
- Re-use mocks from tx-item-relationship-service/local/deployment/full-irs for first draft and then replace the mocks with the actual services
  - https://github.com/eclipse-tractusx/sldt-semantic-hub
  - https://github.com/eclipse-tractusx/sldt-digital-twin-registry
  - https://github.com/eclipse-tractusx/managed-identity-wallet
- use testdataset of DEV
