### ISSUE TITLE
API Endpoints Auth switch from OAuth  to API Keys

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#318]
**As** company admin
**I want** to deploy the IRS in a company context 
**so that** abe to authenticate the IRS over local auth without external dependencies 

## Hints / Details

- ...

### Outcome
- ...
### Acceptance Criteria
- API endpoints are auth using API keys 

## Out of Scope

- ...

**Comment by jzbmw** [comment]
duplicate to #259
