### ISSUE TITLE
Improve code formatter settings

### ISSUE THREAD

**Issue by dsmf** [eclipse-tractusx/item-relationship-service#319]
**As** developer
**I want** formatter settings to be optimized and closer to [Google Java Style](https://google.github.io/styleguide/javaguide.html)
**so that** the formatting does not lead to long lines with fluent api calls.

![Image](https://github.com/eclipse-tractusx/item-relationship-service/assets/19529362/f08d5bd2-ff71-4733-bc37-acf347b8b349)

## Hints / Details

- On https://confluence.catena-x.net/display/IRS/7.+IRS+Code+Standards we agreed to follow [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html).
- There is an IDE plugin that enforces this style without having to configure the settings https://github.com/google/google-java-format.
- As far as I remember it formats code for fluent APIs better than our current settings avoiding long lines (to be tested).
- Note that if we decide to use the plugin, the story #271 will be obsolete.
- investigation has taken place whether we can use the google-java-format plugin instead of a config file (would avoid accidential differences) 
- and whether this would format fluent API calls in a way that does not consume so much horizontal space (and still is good to read)
- if we cannot use the plugin or it does not format fluent APIs well then investigate whether there is a code style setting that would lead to better formatting here
- try maven approach first

### Outcome
- ...
### Acceptance Criteria
- [ ] Plugin has been installed
- [ ] Documented on readme.md

## Out of Scope

- ...

**Comment by jzbmw** [comment]
@dsmf is there a specific change which can be taken in the code formatter settings? 
I want to get it down to a concrete acceptance criteria to pass along the team

**Comment by jzbmw** [comment]
@dsmf I thought you have already investigated. Shall be the investigation part of the story. 

I thought you already have a state, or changes you would like.

**Comment by ds-jhartmann** [comment]
Planning 2:
- google code formatter plugin does not seem to do the trick ->increase margin in our code formatter to >= 200 for better readbility

**Comment by ds-psosnowski** [comment]
Documentation for contributors has been updated for how to use new formatting plugin. (waiting for merge) 
Following task will be to format legacy code and then apply new config to `checkstyle.xml` file: 
``` 
<module name="Indentation">
            <property name="basicOffset" value="2"/>
            <property name="braceAdjustment" value="0"/>
            <property name="caseIndent" value="2"/>
            <property name="throwsIndent" value="2"/>
            <property name="lineWrappingIndentation" value="2"/>
            <property name="arrayInitIndent" value="2"/>
        </module>
```
New code formatting cannot be enabled yet since old code format would volatile new rules and result in failed build.
