### ISSUE TITLE
Concept: Provisioning of contract negotiation and contract agreement for assets

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#322]
**As** Trace-X
**I want** contract negotiation and contract agreements information for received assets  
**so that** I am able to audit the data contracts, assets were retrieved 

## Branch 
- https://github.com/catenax-ng/tx-item-relationship-service/tree/chore/%23322-Provisioning-of-contract-negotiation-and-contract-assessment-for-assets

## Hints / Details
- child of eclipse-tractusx/sig-release#218
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/370

####  Collaboration Meeting with Trace-X 

1.  Collecting contract agreement ids for assets is mandatory for Trace-X. Agreed to enable and disable the collection of ids for performance reasons could be managed over an API parameter. Wish would be to have this parameter activated by default.
2. To make this easier to handle and to have non-invasive code changes, Trace-X prefers the non-normalized form of implementation. For each submodel and each AAS shell, the id should be available in the JobResponse even if it is identical several times. 
3. Trace-X has access to the EDC Consumer Management API of IRS 
4. Access to EDC management api should be covered by IRS Client Library  

### Acceptance Criteria
- [x] Collaboration Meeting with Trace-X has been conducted and results are documented
- [ ] Concept available which covers 
  - [ ]  Provisioning of required identifications for contract negation and contract agreement id edc:ContractAgreementDto@id
  - [ ]  IRS provides the ContractAgreeementId for data asset in JobResponse on demand 
  - [ ]  How the business app can request the edc:ContractAgreement and ContractNegotation Payload to visualize the required results 
  - [ ]  Specify the time period the ContractAgreeementId  payload  and ContractNegotation payload should be accessible and be available for the business app  - according to that decide if information should be stored in IRS or stored in the EDC. How long does the EDC store this information and is it sufficient to store this in the EDC - (10 years according to law)
 - [ ]  Tickets are created in backlog

## Out of Scope

- ...

##  Clarification 
- [ ]  Can Trace-X access the management API of the IRS EDC? 
- [ ] Should the EDC Management API of the IRS be configured in the business application or should the url be supplied via the JobResponse? 
- [ ] Does the business app have access to the management API of the EDC configured for the IRS

**Comment by ds-jhartmann** [comment]
Since Trace-X (or any other service which uses the IRS) are the ones managing the IRS EDC, another suggestion would be to extend the registry/edc library with the required requests to the EDC, so Trace-X is able to gather the contracts themselves.

**Comment by mkanal** [comment]
## Decision @jzbmw and @ds-jhartmann 
* Provisioning of ContractAgreementDto:@Id via IRS JobReponse. This is the unique artifact which is required to resolve the   ContractAgreement / ContractNegoation and Asset 
* How to resolve the EDC url and API  Key  of the IRS EDC via API Key ? 


### Contract neg id and agreement id are stored in the job response - access to the respective content is via the EDC Management API
#### Pro 
* No need to store contract data in IRS 
#### Contra 
* Trace-X MUST have access to EDC of IRS - no good design as IRS proxies the access to EDC in general 
### Job response covers the complete payload of contract agreement and negotiation 
#### Pro 
* Contact must not be stores in IRS 
* Data are forwarded to consumer in general 
#### Contra 
* Exponential grow of JobResponse on complex data chains 



# Specification 
edc:ContractAgreementDto 
"@id": "YjA4NjdmMjgtYWMwMC00OTdiLTliMTItNGEzZDdkYjk4YmEw:cmVnaXN0cnktYXNzZXQ=:YWI2MTY5ZDctNzdiYi00YTQ1LTljZTYtZTUzZjhjM2MwYTFm"

**Comment by mkanal** [comment]
@jzbmw 
# Collaboration Meeting with Trace-X 
Outcome 
1.  Collecting contract agreement ids for assets is mandatory for Trace-X. Agreed to enable and disable the collection of ids for performance reasons could be managed over an API parameter. Wish would be to have this parameter activated by default.
2. To make this easier to handle and to have non-invasive code changes, Trace-X prefers the non-normalized form of implementation. For each submodel and each AAS shell, the id should be available in the JobResponse even if it is identical several times. 
3. Trace-X has access to the EDC Consumer Management API of IRS 
4. Access to EDC management api should be covered by IRS Client Library
