### ISSUE TITLE
"submodelDescriptors" in "shells" exist for jobs requested without aspects

### ISSUE THREAD

**Issue by ds-alexander-bulgakov** [eclipse-tractusx/item-relationship-service#325]
## Description
IRS-jobs can be started without any aspects. This jobs are expected to not contain any _submodelDescriptors_ in _shells_ which is currently not always the case. Detected on DEV.
Detected by tavern-test TRI-912.

## Current behaviour
_submodelDescriptors_ in _shells_ are responsed for some shells:

![Image](https://github.com/eclipse-tractusx/item-relationship-service/assets/114988128/76ade285-50e1-427a-90c1-d01e6e6b3138)

## Expected behavior
_submodelDescriptors_ in _shells_ are empty.

## Steps to reproduce the Bug
- Request IRS job without aspects e.g.:
{code}
{
	"key": {
		"globalAssetId": "urn:uuid:6d505432-8b31-4966-9514-4b753372683f",
		"bpn": "BPNL00000003AVTH"
	},
	"collectAspects": true,
	"lookupBPNs": false,
	"depth": 1,
	"direction": "downward"
}
{code}
- Check the _submodelDescriptors_ in _shells_.

**Comment by ds-alexander-bulgakov** [comment]
Issue could not be reproduced on DEV anymore, the fix was successful. No _submodelDescriptors_ in shells are present anymore for IRS-jobs requested without aspects. Retested with several parameter and depths.

Ticket is ready for PO-review, FYI @jzbmw.

**Comment by jzbmw** [comment]
approved
