### ISSUE TITLE
Add support for the Tractus-X EDC EDR management API

### ISSUE THREAD

**Issue by ds-jkreutzfeld** [eclipse-tractusx/item-relationship-service#328]
**As** an IRS operator ,
**I want** the IRS (and the EDC client library) to use the EDR management API instead of the EDR callbacks ,
**so that** I can avoid having an unsecured callback endpoint in operation.

## Hints / Details

- The Tractus-X EDC offers an EDR management. The EDRs are stored on the EDC side and expired tokens are renewed automatically. When data access is required, you can easily retrieve the EDR via the EDC API. For more information, please refer to https://github.com/eclipse-tractusx/tractusx-edc/blob/main/docs/samples/edr-api-overview/edr-api-overview.md.
- Currently, the EDR callback mechanism is used and a callback endpoint is provided by the edc-client automatically. This endpoint is insecure in the default configuration. For the IRS, it is secured using a different port and infrastructure mechanics. However, this is not suitable for all environments.
- The EDR callback mechanism could be replaced (or extended) with the EDR management API.

I have already provided a possible implementation in this branch: https://github.com/eclipse-tractusx/item-relationship-service/tree/feature/use-edc-edr-management

Please check whether this is suitable and could be used.

### Outcome
- The EDR management API should be (optionally) usable in the client library and IRS. 
### Acceptance Criteria
- [ ] It is possible to use the EDR management API instead of the EDR callback for the IRS and in the EDC client library in general.

## Out of Scope

- ...

**Comment by jzbmw** [comment]
@ds-jkreutzfeld  Hey Jan, 
nice to hear from you. Thank you for this ticket. We will have a look.
Greetings

**Comment by mkanal** [comment]
Duplicate
