### ISSUE TITLE
Identify Submodels also in the IRS owner's registry

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/item-relationship-service#338]
**As** a PURIS user ,
**I want** to be able to retrieve also submodels in my own registry for the given Catena-X ID of the child items,
**so that** I am able to retrieve submodels from my partner's and my own twin.

## Discussions 
1. Idea 1: Additional semantic model for relationship of twins on same level. SLUAB child -> parent / SLUBB parent -> child / SingleLevelXasBuilt twin <-> twin 
2. Idea 2:  Additional business logic in IRS to detect twin for same uuid on customer level  
- Search for the twin directly in the customer's DTR (find out BPN via SingleLevelUsageAsPlanned). 
- Include the material in the customer's SingleLevelBomAsPlanned. The IRS then consumes this by first querying downwards and then upwards relationships again

## Hints / Details

- PURIS has information that belong to both, customer and supplier but should refer to the same digital twin.
- The twins need to be provisioned according to Industry Core KIT.
- The following graphic provides an overview:
  - Given the customer manufactures the material "Control Unit", the customer IRS traverses the SingleLevelBomAsPlanned to identify also the material "Semiconductor" of his supplier based on the Catena-x ID and the BPN (EDC Discovery). As a result thesSubmodels "Supplier Production Output" and "Supplier Stock" have been found.
  - The IRS does NOT find the material "Semiconductor" of the customer. Thus, the Submodels "Customer Demand" and "Customer Stock" may not be found. -> To find this information, the IRS must lookup the same Catena-X ID (Global Asset ID) in the customer's own Digital Twin Registry. A BPN Discovery usage is not needed for this step.

![image](https://github.com/eclipse-tractusx/item-relationship-service/assets/116013795/9e974860-7fa0-4819-b109-df57dca6c940)

### Outcome
- The IRS considers the submodels of the customer's and supplier's twins that represent the same asset.
### Acceptance Criteria
- [ ] Concept covering following details is available for further discussions 
   - [ ] The IRS finds the submodels of the supplier's twin for each child item (following the already existing access restrictions).
   - [ ] The IRS finds the submodels of the customers twin for each child item (following the already existing access restrictions).

## Out of Scope

- A third party providing information about the same asset with a third twin.

**Comment by jzbmw** [comment]
@tom-rm-meyer-ISST thank you for your issue. We'll have a look and let you know how we proceed with this

**Comment by jzbmw** [comment]
Focus time due is Release 24.05

**Comment by mkanal** [comment]
Label DISCUSSION_NEEDED was removed. Initially we start with a concept as a base for further discussions.

**Comment by ds-jhartmann** [comment]
To be clarified:
- For which bom lifecycles and direction is this applicable?
- Are there only certain aspect models which have to be requested in this manner or does this apply to all aspect models?

**Comment by tom-rm-meyer-ISST** [comment]
@ds-jhartmann thanks for reaching out.

We discussed the requirement again and don't need it anymore. Actually this seems also to be an anti pattern to use the IRS + EDC to get data out of our own twins.

Can be closed from my point of view (closing is up to you :)).

**Comment by mkanal** [comment]
Wontfix
