### ISSUE TITLE
Sonar Quality Gate Issues

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/item-relationship-service#341]
**As** developer,
**I want** no sonar quality issues,
**so that** maintainability and overall code quality is meeting our standards.

## Hints / Details
- Sonar Quality Gate is failing due to a bug
- https://sonarcloud.io/summary/new_code?id=eclipse-tractusx_item-relationship-service

![Image](https://github.com/eclipse-tractusx/item-relationship-service/assets/48311334/74438210-6f8d-43eb-9101-9790839321f6)

### Outcome
- [x] Quality gate in sonar reports green state "Passed"

### Acceptance Criteria
- [x] Sonar Issues are fixed

## Out of Scope

- ...

**Comment by dsmf** [comment]
https://github.com/catenax-ng/tx-item-relationship-service/pull/827

**Comment by mkanal** [comment]
Evidence is given and this is resolved. https://sonarcloud.io/summary/new_code?id=eclipse-tractusx_item-relationship-service
@jzbmw  ready for PO acceptance.
