### ISSUE TITLE
IRS response with 503 for some requests

### ISSUE THREAD

**Issue by ds-alexander-bulgakov** [eclipse-tractusx/item-relationship-service#342]
## Thoughts 
- Suppose that 503 is returned by ArgoCd / nginx infrastructure, maybe pod is restarting in this case. 
- Resource allocation of irs has to be checked 
- Check why irs is restarting unexpected 

## Description
During testing with tavern-tests a few tests failed due to _*503* Service Temporarily Unavailable_ beginning from the 8th of december, which not appeared before. Seems like there is a restart due to too much requests. The 503 responses occured at the time of peak:
![Image](https://github.com/eclipse-tractusx/item-relationship-service/assets/114988128/8d5ebc63-2867-44ed-b063-e6d6ae2e1a57)

## Current behaviour
The IRS sometimes is not available, requests are responsed with _*503* Service Temporarily Unavailable_.

## Expected behavior
(?) Here we have to discuss about the reason and what the best resolution would be! TBD

## Steps to reproduce the Bug
Not easy to reproduce but either:
- try to create a lot of big jobs and request them with jobId or
- start [tavern tests](https://github.com/catenax-ng/tx-item-relationship-service/actions/workflows/tavern.yml)

**Comment by ds-alexander-bulgakov** [comment]
Hi @jzbmw,
FYI for further prioritization. We should discuss this topic within the team after investigation of the reason.

**Comment by ds-jhartmann** [comment]
Planning 2
- clarify if this is still occurring
- 503 hints at kubernetes pod restarts -> investigate why the IRS pod is restarting (perhaps resource limitations)
