### ISSUE TITLE
Testautomatisation for local development and CI/CD pipeline using mocks

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/item-relationship-service#344]
**As** developer,
**I want** to have a mocked and fully automated testing-infrastructure,
**so that** I can develop more efficiently.

## Link 
- child of https://github.com/eclipse-tractusx/sig-release/issues/217
- relates to - relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/223
- child of - eclipse-tractusx/sig-release#418

## Hints / Details
- Testing is currently done by unit tests and cucumber tests which are executed on the ArgoCD Cluster, provided by the CatenaX consortia. This environment is not accessible to everyone and will no longer be available with the end of the consortia phase.
- Integration and E2E Test scenarios should be defined and implemented which cover the entire IRS flow. Responses of third-party services should be mocked
- all systems on the main branch
- prioritize: EDC, DTR, discovery Services

### Outcome
- ...
### Acceptance Criteria
- [x] Integration tests, covering IRS communication with other systems, are implemented using mock data
- [x] E2E tests, covering the IRS flow, are implemented using mock data

## Out of Scope

- ...

**Comment by jzbmw** [comment]
Planning 2: List of Systems to be prioritized

**Comment by ds-jhartmann** [comment]
Created WireMock Integration tests in https://github.com/catenax-ng/tx-item-relationship-service/pull/744

**Comment by ds-jhartmann** [comment]
Ready for PO acceptance @jzbmw
