### ISSUE TITLE
Policy store is designed to be associated with allowedBpn

### ISSUE THREAD

**Issue by ds-ext-kmassalski** [eclipse-tractusx/item-relationship-service#345]
**As** ... ,
**I want** ... ,
**so that** ... .

## Hints / Details

- ...

### Outcome
- ...
### Acceptance Criteria
- ...

## Out of Scope

- ...

_Currently, allowed api bpn is used as a 'primaryKey' in policy store. We moved authentication to use API Keys, and API bpn is not supported anymore. This brings requirement to reimplement Policy Store to not use allowed bpn anymore.

Side note: Not known why it was designed to be associated with allowedBpn. Looking at the code it doesn't make much sense, only one BPN was possible to configure anyway._

Please refer to : https://github.com/eclipse-tractusx/item-relationship-service/issues/199
Business requirement is to define policy for one or multiple BPNLs. 
API request has to be extended in #199 to accept a list of BPNLS. In case BPN is used as primary key for policies this has to be refactored as well using a ID which is unique for a certain policy. 
@jzbmw  Recommendation is to close this issue.

**Comment by mkanal** [comment]
@ds-ext-kmassalski
Please adjust this ticket to the defined story template.

**Comment by jzbmw** [comment]
duplicate
