### ISSUE TITLE
Update License Headers

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/item-relationship-service#349]
**As** a eclipse project ,
**I want** to have up-to-date license information ,
**so that** legal requirements are met.

## Hints / Details
- child of eclipse-tractusx/sig-release#218
- new year format should be 2021,2024 instead of 2021,2022,2023,2024
- do that on a good point in time 
- https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02

### Outcome
- ...
### Acceptance Criteria
- [x] License headers are updated to 2024
- [ ] License header templates are updated to 2024

## Out of Scope

- ...

**Comment by dsmf** [comment]
In some files there is

`
 * Copyright (c) 2021,2022,2023
 *       2022: ZF Friedrichshafen AG
 *       2022: ISTOS GmbH
 *       2022,2023: Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
 *       2022,2023: BOSCH AG
 * Copyright (c) 2021,2022,2023 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
`

Do we update both Copyright lines or only the line that contains "Contributors to the Eclipse Foundation"?

**Comment by dsmf** [comment]
**Regex**: "Copyright \(c\) (20..,)*(20..) Contributors to the Eclipse Foundation$"
**Replace with**: "Copyright (c) 2021,2024 Contributors to the Eclipse Foundation"

**Comment by dsmf** [comment]
**branch**: https://github.com/catenax-ng/tx-item-relationship-service/tree/chore/349-update-license-headers/

**pull request**: https://github.com/catenax-ng/tx-item-relationship-service/pull/712

**Comment by dsmf** [comment]
As discussed in the review we should also change the first part of the license header:
```
^ \* Copyright \(c\) 2022,2024$
^ \*       2022: ZF Friedrichshafen AG$
^ \*       2022: ISTOS GmbH$
^ \*       2022,2024: Bayerische Motoren Werke Aktiengesellschaft \(BMW AG\)$
^ \*       2022,2023: BOSCH AG$
^ \* Copyright \(c\) 2021,2024 Contributors to the Eclipse Foundation$ 
```

**Comment by dsmf** [comment]
@jzbmw just mentioned that BMW should be in the new files template too. For this there is a new PR here:

https://github.com/catenax-ng/tx-item-relationship-service/pull/734

**Comment by dsmf** [comment]
**Outcome:**

Existing headers were updated to match the following: 

```
/********************************************************************************
 * Copyright (c) 2022,2024
 *       2022: ZF Friedrichshafen AG
 *       2022: ISTOS GmbH
 *       2022,2024: Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
 *       2022,2023: BOSCH AG
 * Copyright (c) 2021,2024 Contributors to the Eclipse Foundation
```

Checkstyle adjusted accordingly.

Checkstyle adjusted that new files must at least contain the following line:

```
 * Copyright (c) 2021,2024 Contributors to the Eclipse Foundation
```

The company specific copyrights are optional.

The following is also valid:

```
/********************************************************************************
 * Copyright (c) 2022,2024 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
 * Copyright (c) 2021,2024 Contributors to the Eclipse Foundation
```
