### ISSUE TITLE
Setup environments after reset of INT portal on 17.01.2024

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#355]
**As** Team
**I want** to re-setup trace apps on all infected systems after reset of portal  
**so that** reduce the outage because of a portal reset to a limit 

# Clarification 
- [ ] In case we switch to API Keys before portal reset there seems not the be any changes regarding the reset of portal 
  - [ ] Setup EDC and SSI Wallet 

## Dependency 
- related to https://github.com/eclipse-tractusx/traceability-foss/issues/552

## Hints / Details
- [x] Reset of portal application
- [x] Reset of registration application
- [x] Reset of Keycloak IdP instances
- [x] Reset of EDC discovery service
- [x] Reset of Managed Identity Wallet (MIW)
-	(Re-)register your company (in case the company account is still needed) (["how to"](https://portal.int.demo.catena-x.net/documentation/?path=docs%2F01.+Onboarding%2F02.+Registration%2F02.+Add+Company+Data.md))
-	(Re-)register users (["how to"](https://portal.int.demo.catena-x.net/documentation/?path=docs%2F03.+User+Management%2F01.+User+Account%2F03.+Create+new+user+account+%28single%29.md))
-	Register connectors (["how to"](https://portal.int.demo.catena-x.net/documentation/?path=docs%2F02.+Technical+Integration%2F01.+Connector+Registration%2F02.+Connector+Registration.md))
-	Register apps (["how to"](https://portal.int.demo.catena-x.net/documentation/?path=docs%2F04.+App%28s%29%2F02.+App+Release+Process))
-	Execute app subscriptions (["how to"](https://portal.int.demo.catena-x.net/documentation/?path=docs%2F04.+App%28s%29%2F05.+App+Subscription%2F03.+Subscription+Overview+%28App+Provider%29.md))
-	Activate app subscriptions (["how to"](https://portal.int.demo.catena-x.net/documentation/?path=docs%2F04.+App%28s%29%2F05.+App+Subscription%2F04.+Subscription+Activation+%28App+Provider%29.md))
-	SSI Credential Requests (["how to"](https://portal.int.demo.catena-x.net/documentation/?path=docs%2F06.+Certificates%2F01.+UseCase+Participation.md))

# Infected systems 
- [x] DEV IRS
- [x] INT IRS

### Outcome
- ...
### Acceptance Criteria
- [x] IRS is up and running after portal reset 
- [ ] Smoke tests are conducted on each system 
- [x] Insomnia collection is up and running 
- [x] Setup EDC and SSI Wallet 
- [x] Vault is updated with new tokens and urls   

## Out of Scope

- ...

**Comment by mkanal** [comment]
@jzbmw 
We have to wait for that organization IRS is registered in the portal. 

fyi
@jjeroch

**Comment by ds-jhartmann** [comment]
With the new Portal, we need to create a Technical User for each System, we interact with. That means that we need a separate User for 
- Semantic Model Management (user configured via `spring.security.oauth2.client.registration.common`)
- BPDM Pool (user configured via `spring.security.oauth2.client.registration.common`)
- Dataspace Discovery (user configured via `spring.security.oauth2.client.registration.portal`)
- Identity Wallet Management (only configured in EDC, not relevant for IRS)

With the current configuration of IRS it is not possible to set a separate User for BPDM Pool, so a change in implementation is required. 
PBI created to add this: https://github.com/eclipse-tractusx/item-relationship-service/issues/378

**Comment by ds-jhartmann** [comment]
@ds-alexander-bulgakov can you please verify that DEV and INT are working again after the poral reset?

**Comment by ds-alexander-bulgakov** [comment]
Update: During testing on INT authentication issues of DiscoveryFinder-user were detected. @ds-jhartmann will take over this topic.

**Comment by ds-jhartmann** [comment]
Provided a fix for the authentication issues on INT https://github.com/catenax-ng/tx-item-relationship-service/pull/749
