### ISSUE TITLE
Decentral Registry Update to 24.05 Release

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#359]
**As** everyone,
**I want** to update the Registry to the R24.05 state,
**so that** a working System exists.

## Link
- child of eclipse-tractusx/sig-release#446
- relates to https://github.com/eclipse-tractusx/traceability-foss/issues/599

## Hints / Details
- https://github.com/eclipse-tractusx/sldt-digital-twin-registry/releases/tag/digital-twin-registry-0.4.9-RC2
- Currently the info is, that no API Changes are to be expected on data consumption side
- On Data Provisioning side we shall check for changes during PI12 and see how that affects our IRS Product
Feature
- https://github.com/eclipse-tractusx/sldt-digital-twin-registry

### Acceptance Criteria
- [x] Version for R24.05 is integrated in the IRS
- [x] IRS job is running successfully
- [x] Asset Adminstration Shell v3.1 s fully supported

## Out of Scope

- ...

**Comment by mkanal** [comment]
Remove status "BLOCKED" as new R24.5 state of dDTR is present

**Comment by ds-jhartmann** [comment]
Planning 2:
- update Registry on DEV and test the Testdata upload and IRS flow
- I dont expect breaking changes, but if something occurs, fix it

**Comment by dsmf** [comment]
pull request: https://github.com/catenax-ng/tx-item-relationship-service/pull/829

**Comment by dsmf** [comment]
both PRs approved and merged

**Comment by mkanal** [comment]
# Test 
- Import Insomnia Collection https://github.com/catenax-ng/tx-item-relationship-service/blob/main/local/testing/request-collection/IRS_Request_Collection.json
-

**Comment by mkanal** [comment]
@ds-ext-kmassalski it is incomprehensible to me that the submodel descriptors are dependent on the added aspects. This does not seem to be implemented correctly.

**Comment by mkanal** [comment]
@jzbmw 
For missing aas standard conformity, I have created a new issue https://github.com/eclipse-tractusx/item-relationship-service/issues/510
The functionality is implemented as expected. 
Ready for PO acceptance.
