### ISSUE TITLE
Detect improvements in arc42 documentation for external contributors

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#362]
**As** team member 
**I want** optimization of the ARC42 documentation 
**so that** clear understanding of the architecture, functionality, operation and business case supported by irs 

## Link
- child of https://github.com/eclipse-tractusx/sig-release/issues/452
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/408
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/409
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/410
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/411
## Hints / Details

- ...

### Outcome
- https://github.com/eclipse-tractusx/item-relationship-service/issues/408
- https://github.com/eclipse-tractusx/item-relationship-service/issues/409
- https://github.com/eclipse-tractusx/item-relationship-service/issues/410
- https://github.com/eclipse-tractusx/item-relationship-service/issues/411

### Acceptance Criteria
- [x] Teams conduct a knowledge transfer workshop (2h) 
- [x] Detection where information is missing or not in adequate level 
- [x] Detect which sections could be improved and what could be improved 
- [x] Create pbis for improvement tasks 

## Out of Scope

- ...

**Comment by ds-jhartmann** [comment]
The workshop was conducted and the following improvements detected:

- https://github.com/eclipse-tractusx/item-relationship-service/issues/408
- https://github.com/eclipse-tractusx/item-relationship-service/issues/409
- https://github.com/eclipse-tractusx/item-relationship-service/issues/410
- https://github.com/eclipse-tractusx/item-relationship-service/issues/411

**Comment by mkanal** [comment]
@jzbmw LGFM please review thank you very much.
