### ISSUE TITLE
Provisioning of contract negotiation and contract agreement for assets

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#370]
**As** Business app 
**I want** to receive CIDs for negotiated assets OR in case of policy is not valid, the policy of the catalog offer inside a tombstone
**so that** I am able to request the contract agreement over EDC API using the CID 

## Link 
- child of https://github.com/eclipse-tractusx/sig-release/issues/453
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/322

### Outcome
- ...
### Acceptance Criteria
- [x] JobResponse provides ContractAgreementId (CID) for shells and submodels 
- [x] JobResponse provides Tombstone extended with policy information in case of invalid policy 
- [x] New API parameter auditContractNegotiation enables and disables audit functionality 
- [x] Documentation (ARC42, API, Admin manual) is extended explaining the new functionality 
- [ ] E2E and INT tests are extended accordingly 
- [x] JobResponse parameter  shell/contractAgreementId,  submodels.contractAgreementId , tombstones.policy are set to null 

## Out of Scope

- ...

## Hints / Details
- [ ] Concept https://github.com/catenax-ng/tx-item-relationship-service/blob/main/docs/concept/%23322-Provisioning-of-contractAgreementId-for-assets/%23322-Provisioning-of-contractAgreementId-for-assets.md
- [ ] Tombstone containing policy of catalog offer is added in case UsagePolicyException is throwing during processing
- [ ] JobResponse is extended to provide CID in shells and submodels 
- [ ] EndpointDataReference is extended with CID (ContractAgreementId)
- [ ] EdcSubmodelClientImpl.getSubmodelRawPayload returns Payload of Submodel and CID  
- [ ] Refactor name methods, which provides now complex object instead of String value 
- [ ] ContractNegotiationService adds policy information for catalog item to UsagePolicyException
- [ ] Policy for catalog item is added to Tombstone in SubmodelDelegate
- [ ] DecentralDigitalTwinRegistryService and CentralDigitalTwinRegistryService is updated and refactored accordingly 
- [ ] https://github.com/catenax-ng/tx-item-relationship-service/pull/724

### auditContractNegotiation
- parameter name: auditContractNegotiation 
- parameter value: boolean value 
- parameter default: true 
- parameter description: enables and disables auditing, including provisioning of ContractAgreementId inside submodels and shells objects
- parameter impacts: enables collection of ContractAgreementId in job processing and provides this information in submodelContainers and ShellContainers as well in Tombstone in case policy does not match or other internal error during EDC communication.

**Comment by ds-jhartmann** [comment]
Planning 2:
- regaring the policy inside tombstones: adding it directly might not be the best solution. Consider a more generic approach (e.g. Object Map)

**Comment by ds-alexander-bulgakov** [comment]
Tavern-tests were created, [PR #760](https://github.com/catenax-ng/tx-item-relationship-service/pull/760) has been merged.
