### ISSUE TITLE
[PI13] Transfer to Tractus-X

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/item-relationship-service#371]
**As** open-source project,
**I want** to have all project information inside the GitHub project,
**so that** no project relevant information is hidden in restricted plattforms.

## Links 
- child of https://github.com/eclipse-tractusx/sig-release/issues/212
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/312
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/344
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/223

## Hints / Details

- [Concept #223](https://github.com/eclipse-tractusx/item-relationship-service/blob/main/docs/concept/%23223-Transfer-to-PCWM/%23223-Transfer-to-PCWM.md)
- Sources: JIRA Xray, MIRO, Confluence
- Xray: Test Execution files & Feature Files
- Confluence: ??
- Miro: none

### Outcome
- ...
### Acceptance Criteria
- [x] Content to be transferred to association is known
- [x] Relevant Confluence pages are transferred to GitHub
- [x] Take IP under consideration (Ask POs before moving sensitive information not provided by irs team)
- [x] Confluence pages are moved to archive after migration to GitHub  - mark migrated pages as deprecated 
- [x] Cucumber Feature files and test executions are stored in GitHub
- [x] Cucumber Tests are executed via Github workflow
- [x] Cucumber Test results are uploaded to workflow
- [x] Transfer to association is completed.
- [x] Move HELM Environments from CATENA-NG to Eclipse 

DO NOT DELETE THE XRAY Files in JIRA as this is used on e.V. LATER. 

## Out of Scope
- ...

## Outcome 
- IP Clearance registered 171_IP Clearance_ItemRelationshipService
- https://confluence.catena-x.net/pages/viewpage.action?pageId=136677712

**Comment by ds-jhartmann** [comment]
Also check these workflows. They refer to catena-x specific environments and should be updated/removed.
- https://github.com/eclipse-tractusx/item-relationship-service/blob/main/.github/workflows/BETA-xray-cucumber-integration.yaml
- https://github.com/eclipse-tractusx/item-relationship-service/blob/main/.github/workflows/integration-test-DEV.yaml
- https://github.com/eclipse-tractusx/item-relationship-service/blob/main/.github/workflows/integration-test-DIL.yaml
- https://github.com/eclipse-tractusx/item-relationship-service/blob/main/.github/workflows/integration-test-INT.yaml
- https://github.com/eclipse-tractusx/item-relationship-service/blob/main/.github/workflows/irs-load-test.yaml
- https://github.com/eclipse-tractusx/item-relationship-service/blob/main/.github/workflows/jira-publish-release.yaml
- https://github.com/eclipse-tractusx/item-relationship-service/blob/main/.github/workflows/synch-env-branch.yml
- https://github.com/eclipse-tractusx/item-relationship-service/blob/main/.github/workflows/tavern.yml
- https://github.com/eclipse-tractusx/item-relationship-service/blob/main/.github/workflows/tavern-integration.yml
- https://github.com/eclipse-tractusx/item-relationship-service/blob/main/.github/workflows/xray-cucumber-integration.yaml

**Comment by mkanal** [comment]
@jzbmw  Before moving the features files from Xray to Github we should align with the testmanagment that Xray is not used any more for R24.5

**Comment by mkanal** [comment]
@jzbmw We should directly start this in PI 13 Iteration 1. With the  new test analyst staffed in april 2024  we could directy start moving this and have the opportunity to document the process and make the necessary changes. Right now it is impacted with too much risk.

**Comment by ds-jhartmann** [comment]
### Acceptance Criteria
- [ ] Content to be transferred to association is known
- [ ] Relevant Confluence pages are transferred to GitHub
- [ ] Take IP under consideration (Ask POs before moving sensitive information not provided by irs team)
- [ ] Confluence pages are moved to archive after migration to GitHub  - mark migrated pages as deprecated 
- [x] Cucumber Feature files and test executions are stored in GitHub
- [x] Cucumber Tests are executed via Github workflow
- [x] Cucumber Test results are uploaded to workflow
- [ ] Transfer to association is completed.
- [ ] Move HELM Environments from CATENA-NG to Eclipse

**Comment by mkanal** [comment]
Content to be transferred to Association is defined here: https://confluence.catena-x.net/display/IRS/TRANFER2ASSOCIATION

**Comment by mkanal** [comment]
Review & Tests:

**Comment by ds-jhartmann** [comment]
* [ ]  _Not executed since 3 weeks https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/helm-test-backwards-compatability.yaml_ -> not part of this story
* [ ]  _Not working https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/release.yaml_ -> not part of this story
* [ ]  _Not working https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/update-docs-for-release.yml_ -> not part of this story
* [ ]  _Not working https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/release.yaml_ -> not part of this story
* [ ]  _Not working https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/int-test-automation.yml_  -> not part of this story
* [ ]  _Not working https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/owasp.yml_  -> not part of this story
* [ ]  _Not working https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/publish-swagger-hub.yml_ -> not part of this story
* [ ]  _Not working https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/trivy-image-scan.yml_ -> not part of this story

* [ ]  _Disabled https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/int-setup-testdata.yml_ -> not used
* [ ]  _Disabled  https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/cucumber-integration-test.yaml_ -> not disabled, this is the base workflow for the specific environments
* [ ]  _Not running https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/cucumber-integration-test-DIL.yaml_ -> DIL is not a active environment right now
* [ ]  _Not working https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/cucumber-integration-test-INT.yaml_  -> We do not have INT test cases right now
* [ ]  _Not working https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/tavern.yml_ -> failing because of ESS (https://github.com/eclipse-tractusx/item-relationship-service/runs/26497706080), DEV cases are working. The workflow in itself is working which was the goal of this story
* [ ]  _Disabled https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/tavern-integration.yml_ -> we do not have INT test cases right now
* [ ]  _Please provide cucumber test execution where all cucumber tests are executed successfully_ -> https://github.com/eclipse-tractusx/item-relationship-service/actions/runs/9597500957 (see the artifact or the [report](https://reports.cucumber.io/reports/93e01d62-6730-495a-9279-2e0902c112c6) which is available until 15:00 today) 
* [ ]  _Where to find the environments merged from catenaxng please link branch here_ -> https://github.com/eclipse-tractusx/item-relationship-service/tree/catena-x-environments

**Comment by mkanal** [comment]
PO acceptance in  behalf of @jzbmw .
Move content to association will be done in https://github.com/eclipse-tractusx/item-relationship-service/issues/686.
