### ISSUE TITLE
Update of Shared Services for R24.5 (DiscoveryFinder, Portal Services, EDC DiscoveryService )

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#372]
**As** product 
**I want** update to shared services to version aligned with R24.5
**so that** irs product dependencies to shared services aligned with R24.5

## Link 
- child of https://github.com/eclipse-tractusx/sig-release/issues/446
- relates to https://github.com/eclipse-tractusx/traceability-foss/issues/762

## Hints / Details

- ...

### Acceptance Criteria
- [ ] IRS uses latest stable version of DiscoveryFinder in R24.5 https://github.com/eclipse-tractusx/sldt-discovery-finder/releases/tag/discoveryfinder-0.2.4-RC1
- [ ] IRS uses latest stable version of Portal Services in R24.5 https://github.com/eclipse-tractusx/portal/releases/tag/portal-1.8.0
- [ ] IRS uses latest stable version of Semantic Hub in R24.5 https://github.com/eclipse-tractusx/sldt-semantic-hub/releases/tag/semantic-hub-0.2.1-RC3
- [ ] IRS uses latest stable version of EDC DiscoveryService in R24.5 https://github.com/eclipse-tractusx/portal-assets/releases/tag/v1.8.0
- [ ] Check the wiremocks are compatible to the new api changes 
- [ ] Update the COMPATIBILITY matrix 

## Out of Scope

- ...

![image](https://github.com/eclipse-tractusx/item-relationship-service/assets/100209308/3149c143-7544-4081-93e2-909d94444c51)

**Comment by mkanal** [comment]
@jzbmw  BLOCKED was removed as the updates are available now.

**Comment by ds-jhartmann** [comment]
Planning 2:
- Check the changelogs of the services for changes which would introduce incompatibility
- Verify that the DEV wiremock for the discovery Services are still up-to-date
