### ISSUE TITLE
IRS Notification and EDC Token Callback endpoints should be secured by API-Key

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/item-relationship-service#391]
**As** an IRS operator,
**I want** to have all endpoints secured,
**so that** no malicious actor can inject data into the system.

## Hints / Details
- IRS exposes certain endpoints on a configurable "trusted-port". Some of these endpoints are only available inside the Kubernetes namespace and not accessible from the outside, so it is not required to add additional security.
- Endpoints called by EDC after Negotiation and by ESS Notifications are are publicly available but currently not secured in any way. Since we switched to API-Keys for IRS authentication, we should secure these endpoints.

## Acceptance Criteria
- [ ] Endpoint /ess/notification/receive is secured by API-Key
- [ ] Endpoint /internal/endpoint-data-reference is secured by API-Key

**Comment by ds-jhartmann** [comment]
Planning 2: 
- Add irs auth token to `org.eclipse.tractusx.irs.ess.service.EdcRegistration#registerAsset`
- Add IRS auth token to `org.eclipse.tractusx.irs.edc.client.EdcControlPlaneClient#startNegotiations`

**Comment by jzbmw** [comment]
Waiting on response from EDC Team.

**Comment by ds-jhartmann** [comment]
EDC Team confirmed that this is not possible. 
Assets only support authentication with OAuth2 to the backend service.
The receiverHttpEndpoint for Transfer Processes does not allow additional Headers for authentication.
