### ISSUE TITLE
Improve Testmanagement in Tractux-X

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#392]
**As** Team
**I want** high quality testmanagement in Tractux-X 
**so that** quality of product development can be sustainably ensured 

## Links
- child of https://github.com/eclipse-tractusx/sig-release/issues/650

## Hints / Details

- select a good set of test's which can be conducted after deployment with the helm test cli 
- 5-10 Tests with helm
- see #226 

![Image](https://github.com/eclipse-tractusx/item-relationship-service/assets/100209308/dfb2102f-c1e4-4a5c-ad7c-7db29933389e)

### Outcome
- you have a understanding what is possible with helm test 
- you know what is possible with helm test 
- you have an idea of how we can use helm test for E2E testing

### Acceptance Criteria

- [ ] Improve IRS Helm chart with Helm Test
- [ ] Summary/identify of what can be tested with helm test (e.g. tavern, functional, E2E, starting a Job, ...) 
- [ ] Interface contract definition is done 

## Out of Scope

- ...

**Comment by jzbmw** [comment]
@mkanal I think it is a duplicate to --> https://github.com/eclipse-tractusx/item-relationship-service/issues/375
What do you think?

**Comment by mkanal** [comment]
Wontifx is resolved with #226
