### ISSUE TITLE
Improved clarity and readability of the repository README.md file

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#393]
**As** team
**I want** well maintained and clarity  project README.MD
**so that** external contributors gets a quick and comprehensible  overview of the product

## Hints / Details
- [x] https://gitlab.com/apparmor/apparmor  is a good practice

### Outcome
- ...
### Acceptance Criteria
- [x]  Align layout to those of product apparmor as far as compliant with the TRGs https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1
- [x] Describe Source Layout of repository
  - [x] Issues 
  - [x] Conversations/Discussions 
  - [x] etc. 
- [x] Describe IRS Testsuites (transparent)
  - [x] Add Cucumber and Tavern Test description 
  - [x] Regression testing 
  - [x] Functional and module testing 
  - [x] Unit testing and reporting 
  - [x] Load Testing Gatling
  - [x] Stress Tests and Smoke Tests 
  - [x] Link to version matrix 

## Out of Scope

- ...

**Comment by ds-jhartmann** [comment]
Planning 2:
Make sure that the README aligns with TRGs https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1

**Comment by ds-alexander-bulgakov** [comment]
Cucumber and tavern README added in [PR #781](https://github.com/catenax-ng/tx-item-relationship-service/pull/781).

**Comment by dsmf** [comment]
- [ ]  Align layout to those of product apparmor
- [ ] Describe Source Layout of respository
- [ ] Describe how to Getting in Touch
- [ ] Matrix Chat
- [ ] Issues
- [ ] Conversations
- [ ] etc.
- [ ] Describe IRS Testsuites (transparent )
  - [ ]     Add Cucumber and Tavern Test description
  - [ ]     Regression testing
  - [ ]     Functional and module testing
  - [ ]     Unit testing and reporting
  - [ ]     Load Testing Gatling
  - [ ]     Stress Tests and Smoke Tests

**Comment by mkanal** [comment]
Conversations/Discussions  >> Should link to https://github.com/eclipse-tractusx/item-relationship-service/discussions

**Comment by dsmf** [comment]
As consulted with @ds-jhartmann the **pull request** was opened to eclipse-tractusx:main directly:

https://github.com/eclipse-tractusx/item-relationship-service/pull/456

**Comment by dsmf** [comment]
@jzbmw ready for PO review
