### ISSUE TITLE
Update outdated Submodel Server

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#403]
**As** product
**I want** update the Submodel Server  
**so that** an up to date helm chart and could be used by other products (Trace-X)

## Hints / Details

- [Submodel Server](https://github.com/catenax-ng/tx-item-relationship-service/tree/catena-x-environments/charts/connector/submodelservers)

### Outcome
- ...
### Acceptance Criteria
- [ ] evaluate alternative submodel helm chart for a submodel server
- [ ] update the helm chart

## Out of Scope

- ...

**Comment by ds-lcapellino** [comment]
Official Submodelserver implementations can be found here: https://eclipse-tractusx.github.io/docs-kits/kits/Digital%20Twin%20Kit/Operation%20View%20Digital%20Twin%20Kit

**Comment by ds-jhartmann** [comment]
- Created a simple Spring App to act as submodel server
- Created Helm Chart for this App
PR https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/54
