### ISSUE TITLE
Add BPN to UsagePolicyException   tombstone from CatalogOffer 

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#404]
**As** business app 
**I want** BPNL for a UsagePolicyException  tombstone 
**so that** am able to assign a tombstone with UsagePolicyException and policy to a BPNL

## Hints / Details
- [ ] org.eclipse.tractusx.irs.edc.client.EDCCatalogFacade#mapToCatalogItems
- [ ] catalog.getProperties().containsKey(JsonLdConfiguration.NAMESPACE_EDC_PARTICIPANT_ID

### Outcome
- ...
### Acceptance Criteria
- [ ] In case UsagePolicyException is thrown, BPN is written to UsagePolicyException tombstone if available 
- [ ] businessPartnerNumber is provided inside an UsagePolicyException tombstone if CatalogOffer provides edc:participantId
- [ ] businessPartnerNumber is null if edc:participantId is not provided CatalogOffer 

```
"tombstones": [
  {
    "catenaXId": "urn:uuid:6ce41c0b-c84a-46b0-b4c4-78fce958663d",
    "endpointURL": null,
    "businessPartnerNumber": "<businessPartnerNumber>",
    "policy": {},
    "processingError": {
       "processStep": "UsagePolicyValidation", 
       "errorDetail": "Consumption of asset (itemId) is not permitted as the required catalog offer policies do not comply with defined IRS policies.",
       "lastAttempt": "2024-01-17T09:02:36.648055745Z",
       "retryCounter": 3
    }
  }
],
```

## Out of Scope

- ...

**Comment by jzbmw** [comment]
![Image](https://github.com/eclipse-tractusx/item-relationship-service/assets/48311334/30fcceba-a6a0-4682-aef6-df80719e117c)

**Comment by ds-jhartmann** [comment]
Since we handle the `UsagePolicyException` at `SubmodelDelegate` and `RelationshipDelegate` level, we already have the BPNL of the company, where we want to request data from, available.
By using this BPN, we do not have the need to extract it from the Catalog and can just add it to the tombstone directly.

**Comment by ds-jhartmann** [comment]
A additional point to consider is adding the BPNL to the tombstone message instead of adding another field. If we keep adding field which are only filled in specific cases, the tombstone object will become messy soon. Son instead of 
```
"tombstones": [
  {
    "catenaXId": "urn:uuid:6ce41c0b-c84a-46b0-b4c4-78fce958663d",
    "endpointURL": null,
    "businessPartnerNumber": "<businessPartnerNumber>",
    "policy": {},
    "processingError": {
       "processStep": "UsagePolicyValidation", 
       "errorDetail": "Consumption of asset (itemId) is not permitted as the required catalog offer policies do not comply with defined IRS policies.",
       "lastAttempt": "2024-01-17T09:02:36.648055745Z",
       "retryCounter": 3
    }
  }
],
```
it would be 
```
  {
    "catenaXId": "urn:uuid:6ce41c0b-c84a-46b0-b4c4-78fce958663d",
    "endpointURL": null,
    "policy": {},
    "processingError": {
       "processStep": "UsagePolicyValidation", 
       "errorDetail": "Consumption of asset (itemId) is not permitted for company <businessPartnerNumber>, as the required catalog offer policies do not comply with defined IRS policies.",
       "lastAttempt": "2024-01-17T09:02:36.648055745Z",
       "retryCounter": 3
    }
  }
```

**Comment by ds-alexander-bulgakov** [comment]
Testdata was provided and tavern test created in branch [#404-create-tavern-tests](https://github.com/catenax-ng/tx-item-relationship-service/tree/feature/%23404-create-tavern-tests). Once the feature is successfully deployt on DEV the test can be run.
