### ISSUE TITLE
RestClientExceptions are not caught in BPDMFacade and DecentralDigitalTwinRegistryService

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/item-relationship-service#405]
## Description

Not properly handled exceptions.

## Link 
- child of https://github.com/eclipse-tractusx/sig-release/issues/650

## Current behaviour
When the Services called by BPDMFacade or DecentralDigitalTwinRegistryService throw HTTP Errors, the corresponding RuntimeExceptions are not caught. 

## Expected behavior
- The RuntimeExceptions are caught and handled. 
- The Tests in BpdmWiremockTest and DecentralDigitalTwinRegistryServiceWiremockTest asserting `assertThatThrownBy(() -> <testmethod>).isInstanceOf(HttpClientErrorException.class);` should fail.

## Steps to reproduce the Bug
Run Tests in BpdmWiremockTest or DecentralDigitalTwinRegistryServiceWiremockTest.

**Comment by dsmf** [comment]
DecentralDigitalTwinRegistryServiceWiremockTest  already done by #214

**Comment by dsmf** [comment]
there is also a TODO in BpdmWiremockTest referring to this story, is this connected or does this actually belong to another issue?

**Comment by ds-jhartmann** [comment]
Yes, the TODOs are referring to BPDMFacade

**Comment by ds-jhartmann** [comment]
Pulling this in PI12 Iteration 6 as discussed in the daily

**Comment by dsmf** [comment]
### Outcome

- RestClientExceptions are handled correctly in BpdmFacade now. 
  https://github.com/catenax-ng/tx-item-relationship-service/pull/864

**Additionally:**
- ClassCastException in exception handling of EdcSubmodelClientImp#getEndpointReferencesForAsset corrected (returns the exception as failed future now).
https://github.com/catenax-ng/tx-item-relationship-service/pull/864
- Propagates exceptions to have more detail in tombstone (using Either and Exception#addSuppressed).
  https://github.com/catenax-ng/tx-item-relationship-service/pull/865

**Comment by dsmf** [comment]
@mkanal , ready for test

**Comment by mkanal** [comment]
@jzbmw LGFM handling seems to be correct. Ready for PO acceptance.
