### ISSUE TITLE
TRG 4.06 separate notice file for `DockerHub` has all necessary information

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/item-relationship-service#425]
The Notice for Docker images section in the README.md must be moved to a separate dedicated file for both frontend and backend and then reference them in the workflow like [here](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06#github-workflow-step). For more help. Please have a look at [TRG4.06 ](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06)for more info.

Also fixes https://github.com/eclipse-tractusx/item-relationship-service/issues/426

**Comment by ds-jhartmann** [comment]
Moved the docker notice to a dedicated DOCKER_NOTICE.md file in https://github.com/eclipse-tractusx/item-relationship-service/pull/428
The changes will be release as IRS 4.5.1 and irs-helm-6.14.1 later today
