### ISSUE TITLE
Semantic versioning of IRS api

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#440]
**As** product 
**I want** automatic semantic versioning of IRS api 
**so that** external players could deal with the api 

## Hints / Details

- ...

## Acceptance Criteria
- [  ] Semantic and automated irs api versioning 
- [  ] Suggestion: irs api is versioned is corresponding with release version     

## Out of Scope

- ...

**Comment by jzbmw** [comment]
might be duplicate

**Comment by mkanal** [comment]
Already implemented
