### ISSUE TITLE
Update Testdata set with Industry Core 2.0.0 compatibility

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#488]
**As** team 
**I want** update to the latest test data set
**so that** we are up-to-date

## Link 
- https://github.com/eclipse-tractusx/item-relationship-service/issues/503

## Hints / Details
- https://jira.catena-x.net/browse/TDG-43
- We already know that currently the tavern tests are failing regarding the SLBAB 3.0.0
- Renaming will be clarified until 20th of march Replacing of Aspects 
   - SerialPart --> PartInstance
   - PartAsPlaned -> PartType

-
SingleLevelBomAsBuilt version 3.0.0
```
 {
  "catenaXId" : "urn:uuid:055c1128-0375-47c8-98de-7cf802c3241d",
  "childItems" : [ {
    "catenaXId" : "urn:uuid:055c1128-0375-47c8-98de-7cf802c3241d",
    "quantity" : {
      "quantityNumber" : 2.5,            <<<<
      "measurementUnit" : "unit:litre"    <<<<
    },
    "hasAlternatives" : true,
    "createdOn" : "2022-02-03T14:48:54.709Z",
    "businessPartner" : "BPNL50096894aNXY",
    "lastModifiedOn" : "2022-02-03T14:48:54.709Z"
  } ]
}
```

SingleLevelBomAsBuil version 3.0.0
```
{
  "catenaXId" : "urn:uuid:055c1128-0375-47c8-98de-7cf802c3241d",
  "childItems" : [ {
    "catenaXId" : "urn:uuid:055c1128-0375-47c8-98de-7cf802c3241d",
    "quantity" : {
      "value" : 20.0,      <<<<
      "unit" : "unit:piece" <<<<
    },
    "hasAlternatives" : false,
    "createdOn" : "2022-02-03T14:48:54.709Z",
    "businessPartner" : "BPNL50096894aNXY",
    "lastModifiedOn" : "2022-02-03T14:48:54.709Z"
  } ]
}
```

## Acceptance Criteria
- [x] Update to new test data set https://confluence.catena-x.net/download/attachments/98566737/CX_Testdata_v1.7.0_PartInstance.zip?version=1&modificationDate=1710484971972&api=v2
- [x] Rename attributes within the "quantity" object marked with <<<< within the test data set
- [x] Alter the version of SingleLevelBomAsBuilt to 3.0.0
    - [x] Documentation
    - [x] INT Tests 
    - [x] Tavern Test & Cucumber Test
    - [x] All use cases 
  
## Out of Scope

- ...

**Comment by ds-jhartmann** [comment]
Planning 2:
- prepare a reduced set of testdata 1.7.0
- change SingleLevelBomAsBuilt from 2.0.0 to 3.0.0
- upload to DEV

**Comment by ds-jhartmann** [comment]
@jzbmw According to https://github.com/eclipse-tractusx/item-relationship-service/issues/439, the tavern tests are supposed to be updated with this issue. We did not account for that in the refinement or planning.

Can we clarify how to deal with this in the next daily?

**Comment by dsmf** [comment]
blocks #488

**Comment by mkanal** [comment]
> * DONE - prepare a reduced set of testdata 1.7.0
> * DONE - change SingleLevelBomAsBuilt from 2.0.0 to 3.0.0
> * DONE - upload to DEV
> * DONE - Update to new test data set https://confluence.catena-x.net/download/attachments/98566737/CX_Testdata_v1.7.0_PartInstance.zip?version=1&modificationDate=1710484971972&api=v2
> * DONE - Rename attributes within the "quantity" object marked with <<<< within the test data set
> * DONE - Alter the version of SingleLevelBomAsBuilt to 3.0.0
> 
> 1.7.0 is uploaded to DEV and Job can be registered:
> 
> ```
> {
> 	"aspects": [
> 		"urn:samm:io.catenax.single_level_bom_as_built:3.0.0#SingleLevelBomAsBuilt",
> 		"urn:samm:io.catenax.serial_part:3.0.0#SerialPart"
> 	],
> 	"bomLifecycle": "asBuilt",
> 	"collectAspects": true,
> 	"lookupBPNs": false,
> 	"direction": "downward",
> 	"depth": 10,
> 	"key": {
> 		"globalAssetId": "urn:uuid:4235f1cf-d303-4b79-bdb1-7a31526bbabd",
> 		"bpn": "BPNL00000001CRHK"
> 	}
> }
> ```
> 
> Job id: acb6a8c4-a7b5-4ce5-adea-81db30acc9da
> 
> Tavern tests will be fixed in scope of: [#503](https://github.com/eclipse-tractusx/item-relationship-service/issues/503)

BPNL00000001CRHK is incorrect -correct is BPNL00000003CSGV

**Comment by mkanal** [comment]
Test Outcome: 
- Validation for SLUAB 3.0.0 MUST fail as this does not fit the schema https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.single_level_usage_as_built/3.0.0/gen/SingleLevelUsageAsBuilt-schema.json
- BPNL00000001CRHK is incorrect -correct is BPNL00000003CSGV This test might not work.

Please rework @ds-ext-kmassalski

**Comment by mkanal** [comment]
{
	"aspects": [
		"urn:samm:io.catenax.single_level_bom_as_built:3.0.0#SingleLevelBomAsBuilt",
		"urn:samm:io.catenax.serial_part:3.0.0#SerialPart",
		"urn:samm:io.catenax.just_in_sequence_part:3.0.0#JustInSequencePart",
		"urn:samm:io.catenax.batch:3.0.0#Batch"
	],
	"key": {
		"globalAssetId": "{% prompt 'Global Asset ID', 'Please provide \'Global-Asset-ID\' or use default', _.GLOBAL_ASSET_ID, '', false, true %}",
		"bpn": "{% prompt 'bpn', '', _.BPN, '', false, true %}"
	},
	"collectAspects": true
}

**Comment by mkanal** [comment]
@jzbmw  Retesting was successful works as indented. Kindly ask for PO acceptance.
