### ISSUE TITLE
Rename IRS Helm Chart

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/item-relationship-service#489]
**As** operator,
**I want** to have a standardized form of helm charts,
**so that** I can deploy all charts the same way.

## Hints / Details
- Helm Charts should be named after the product name, i.e. the IRS chart name should be `item-relationship-service` (without the -helm suffix)
- Change the description to `Tractus-X Item Relationship Service Helm Chart`

## Acceptance Criteria
- [x] Helm Charts should be named after the product name, i.e. the IRS chart name should be `item-relationship-service` (without the -helm suffix)
- [x] Change the description to `Tractus-X Item Relationship Service Helm Chart`
- [x] Update workflows which use and build the chart
- [x] Update references in documentation

## Out of Scope
- ...

**Comment by dsmf** [comment]
outcome: 
* [x] Helm Charts named after the product name "item-relationship-service"
* [x] Change the description to Tractus-X Item Relationship Service Helm Chart
* [x] Update workflows which use and build the chart
* [x] Update references in documentation
* [x] helm-chart-release.yaml: Step "Get helm charts latest tag version" sorts versions correctly now (`sort -V` for numeric sorting of versions) 
* [x] Tested release workflow in own fork

**Comment by mkanal** [comment]
@jzbmw This could be tested after the release. We will present this in the iteration review.
