### ISSUE TITLE
[ITERATION_6] Update R24.5 RC Versions to latest stable versions

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#496]
**As** team
**I want** finally check if we use the latest versions for shared service
**so that** we are 24.5 ready 

## Link 
- [ ] Trace-X https://github.com/eclipse-tractusx/traceability-foss/issues/762
- [ ] IRS  https://github.com/eclipse-tractusx/item-relationship-service/issues/359
- [ ] relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/358

### Acceptance Criteria
- [x] IRS uses latest stable version of DiscoveryFinder in R24.5 https://github.com/eclipse-tractusx/sldt-discovery-finder/releases/tag/discoveryfinder-0.2.4
- [x] IRS uses latest stable version of Portal Services in R24.5 https://github.com/eclipse-tractusx/portal/releases/tag/portal-1.X.0
- [x] IRS uses latest stable version of Semantic Hub in R24.5 https://github.com/eclipse-tractusx/sldt-semantic-hub/releases/tag/semantic-hub-0.2.1
- [ ] IRS uses latest stable version of EDC DiscoveryService in R24.5 https://github.com/eclipse-tractusx/portal-assets/releases/tag/v1.X.0
- [x]  IRS uses latest stable version of EDC 0.7.0 in R24.5 
- [x] Environments are updated with new Versions (DEV, ..)

**Comment by jzbmw** [comment]
Blocked: See ticket #358

**Comment by ds-jhartmann** [comment]
Planning 2:
- services and IRS implementations should be up to date already (except for EDC)
- check if there are newer versions available

**Comment by ds-jhartmann** [comment]
### Acceptance Criteria
- [x] IRS uses latest stable version of DiscoveryFinder in R24.5 https://github.com/eclipse-tractusx/sldt-discovery-finder/releases/tag/discoveryfinder-0.2.5
- [ ] ~~IRS uses latest stable version of Portal Services in R24.5 https://github.com/eclipse-tractusx/portal/releases/tag/portal-1.X.0~~ No other portal service other than DiscoveryService is used. 
- [x] IRS uses latest stable version of Semantic Hub in R24.5 https://github.com/eclipse-tractusx/sldt-semantic-hub/releases/tag/semantic-hub-0.2.3
- [x] IRS uses latest stable version of EDC DiscoveryService in R24.5 https://github.com/eclipse-tractusx/portal-backend/releases/tag/v1.8.1
- [x]  IRS uses latest stable version of EDC 0.7.0 in R24.5 
- [x] Environments are updated with new Versions (DEV, ..)

**Comment by mkanal** [comment]
PO acceptance in behalf of @jzbmw
