### ISSUE TITLE
[R24.5] SAST / DAST PCWM conformity : TRG 8.01 & TRG 2-6

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#499]
**As** product
**I want** migrate from deprecated S/DAST to new proposed S/DAST toolings
**so that** compliant to the TRGs for R24.5

## Hints / Details
Please migrate to the new tools, which means using Static Application Security Testing CodeQl (https://eclipse-tractusx.github.io/docs/release/trg-0/trg-8-01/ ) for software security testing and Software Composition Analysis (https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-6/ ) for analyzing software components. It is also important to change/delete the related GitHub actions.

## Acceptance Criteria
- [x] TRG 8 .1 Veracode is descoped from documentation, cd/cd pipeline, code, KIT docu etc
- [x] TRG 8 .1 CodeQl  is used for SAST including extension documentation, cd/cd pipeline, code, KIT docu etc
- [x] TRG 2.1 Dependabot is used for SCA including extension documentation, cd/cd pipeline, code, KIT docu etc
- [x] TRG 2.1 Veracode is descoped from documentation, cd/cd pipeline, code, KIT docu etc

## Out of Scope

- ...

**Comment by ds-jhartmann** [comment]
See https://github.com/eclipse-tractusx/item-relationship-service/pull/421

**Comment by mkanal** [comment]
Outcome: 
- [x] https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/codeql.yml
- [x]

**Comment by ds-jhartmann** [comment]
We did not change any Dependabot rules, so the Organization default is used. From what I can see, everything works as expected. 
Alerts are enabled:
![image](https://github.com/eclipse-tractusx/item-relationship-service/assets/57985712/21b03a6d-3e0f-42c0-baa4-c98da0c73e43)
