### ISSUE TITLE
Provide Swagger UI on Github Pages

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#500]
**As** a external contributor ,
**I want** a Swagger UI on GitHub Pages,
**so that** I have a detailed overview of provided APIs and are able to download the OpenApi specification.

## Link 
- https://github.com/eclipse-tractusx/item-relationship-service/issues/418

## Hints / Details
- It is not possible to publish our API on SwaggerHub because there are already three APIs published (#418). This is the maximum amount in the free tier. Tractus-X is not planning to upgrade it. Therefore, we have to find an alternative to SwaggerHub. A proposed alternative are the GitHub Pages for each project. (https://eclipse-tractusx.github.io/traceability-foss/docs/)
- An example on how to achieve that, can be found in the EDC repository: https://github.com/eclipse-edc/.github/blob/main/.github/workflows/publish-openapi-ui.yml

## Acceptance Criteria

- Swagger UI is available in the  IRSGitHub Pages: https://eclipse-tractusx.github.io/item-relationship-service/docs/
- KIT documentation must be updated
- 

## Out of Scope

- ...

**Comment by ds-jhartmann** [comment]
Planning 2:
- take a look at how the EDC team did this and re-use it, if possible

**Comment by mkanal** [comment]
@jzbmw Ready for review - swagger ui is present and KIT update was made
