### ISSUE TITLE
Fix tests Tavern + Cucumber Tests 

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#503]
**As** team
**I want** to have working tests
**so that** we could align with the DoD and required quality 

## Acceptance Criteria
- [x] Tavern tests are updated and working refer to comment   https://github.com/eclipse-tractusx/item-relationship-service/issues/439#issuecomment-2003901954
- [x] Cucumber test are updated

## Out of Scope

- ...

## Outcome 
- [x] fix(test):[#503] fix test [TRI-893](https://jira.catena-x.net/browse/TRI-893)

## Branch 
https://github.com/catenax-ng/tx-item-relationship-service/tree/fix/%23503-Fix-tests-Tavern-Cucumber-Tests

**Comment by ds-jhartmann** [comment]
Cucumber tests need also to be fixed

**Comment by ds-jhartmann** [comment]
Planning 2:
- switch to new globalAssetIds from the v1.7.0 Testdata sets
- adjust cucumber tests and expected files
- adjust tavern tests (find out how to adjust them)

**Comment by ds-jhartmann** [comment]
fixed tavern tests in https://github.com/eclipse-tractusx/item-relationship-service/pull/675

**Comment by ds-jhartmann** [comment]
All Cucumber Tests executed successfully:
![image](https://github.com/eclipse-tractusx/item-relationship-service/assets/57985712/61d2b1b0-6e0c-40f1-85e6-5bdcb415ceaf)
All Tavern Tests executed successfully:
![Screenshot 2024-05-28 170657](https://github.com/eclipse-tractusx/item-relationship-service/assets/57985712/fc971e52-6f4a-47af-8542-199694be367e)

**Comment by mkanal** [comment]
PO acceptance in behalf of @ds-jhartmann 
All tests passed before there was a DIM problem. We have propagated the DIM error, which harms execution of int and e2e tests.
Currently, we do not know who to contact.
