### ISSUE TITLE
IRS runs into an out of memory error if instance is running longer then x days

### ISSUE THREAD

**Issue by ds-mwesener** [eclipse-tractusx/item-relationship-service#504]
## Current behaviour
- Trace-X uses irs on its environments. If the irs instances runs longer than a few days including several data imports (20 submodel lookups per run. Approx. 120 submodels a day.

## Expected behavior

- IRS does not throw out of memory exceptions.

## Steps to reproduce the Bug

Let IRS run over the weekend and check instance on monday after a reload of submodels by trace-x.
Please also find log attached.

![image](https://github.com/eclipse-tractusx/item-relationship-service/assets/124587888/c6281abb-61ad-446c-8209-b883bcfe595d)

**Comment by jzbmw** [comment]
Already might have been resolved with raising the RAM limitations from 500mb to 1,5gb
