### ISSUE TITLE
Provide submodeldescriptors in shells for all available submodels in JobReponse

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#510]
**As** irs consumer
**I want** receiver all submodel descriptors 
**so that** I am able to see any submodels related to the twin and not only those which I requested 

## Decision 
- A. Remove shell from JobResponse and deliver only required fields (DPP, Trace-X)
- B. Provide a AAS conform shell in Job Reponse (@mkanal )

## Acceptance Criteria
- [x] IRS provides AAS standard conform result without modifications 

## Out of Scope

- ...

**Comment by ds-kgassner** [comment]
successfully tested - approved from my side

**Comment by ds-kgassner** [comment]
Ready for PO review @mkanal

**Comment by mkanal** [comment]
LGFM PO acceptance in behalf of @jzbmw 

![image](https://github.com/eclipse-tractusx/item-relationship-service/assets/100209308/c7afe337-91f1-41f6-ba53-927d4f50adc4)
