### ISSUE TITLE
[TEST] Integration Tests Policy Store (Happy Path)

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#518]
**As** product
**I want** automatically executed integration tests for policy store covering the happy path
**so that** we are informed about regression errors at the earliest stage, and we have a high level of confidence in the application

## Links 
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/528
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/559
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/560

## Hints / Details

- ...

## Acceptance Criteria
- [x] Integration tests (Cucumber or Tavern) covering policy store happy path executed in Ci/CD pipeline before PR is merged
- [x] Test covers journey
     - [x] Registration of more than 10 different policies for at least 5 BPNLs 
     - [x] Requesting all policies > All registered policies are available for the related BPNLs
     - [x] Update a policy validUntil (valid date)
     - [x] Add BPNL to policy - Check result 
     - [x] Add policyId to given BPNLs  - Check result 
     - [x] Delete at least 3 policies and - Check result
 - [x] Test is linked to a suitable Xray Testplan or new one is created 
 - [x] Test is executed via CI/CD pipeline 

## Out of Scope

- ...

**Comment by mkanal** [comment]
https://github.com/eclipse-tractusx/item-relationship-service/issues/559

**Comment by mkanal** [comment]
@dsmf  Please refer the Xray Tests in JIRA where Gherkin Tests are defined.

**Comment by dsmf** [comment]
### Outcome:

- [x] Test covers journey
    - [x] Registration policies for some BPNLs (https://jira.catena-x.net/browse/TRI-1950)
    - [x] Requesting all policies > All registered policies are available for the related BPNLs (https://jira.catena-x.net/browse/TRI-1950)
    - [x] Update a policy validUntil (https://jira.catena-x.net/browse/TRI-1951, https://jira.catena-x.net/browse/TRI-1952)
    - [x] Add BPNL to policy - Check result (https://jira.catena-x.net/browse/TRI-1953)
    - [x] Add policyId to given BPNLs - Check result (https://jira.catena-x.net/browse/TRI-1954)
    - [x] Delete policies and - Check result (https://jira.catena-x.net/browse/TRI-1955)

Plus in order to test response state setup:
- [x] Fetching policies by BPNLs should fail for invalid BPNLs ()
- [x] Registering a policy without validUntil should fail (https://jira.catena-x.net/browse/TRI-1965)

**Comment by dsmf** [comment]
@mkanal, ready for test

**Comment by dsmf** [comment]
https://jira.catena-x.net/browse/TRI-1987
all policy store api tests successful, the others fail for other reasons not connected to this story

**Comment by mkanal** [comment]
PO acceptance in behalf of @jzbmw. All int tests works as expected.
