### ISSUE TITLE
Json schema validation results are wrong with newest jsonschemafriend library

### ISSUE THREAD

**Issue by ds-ext-kmassalski** [eclipse-tractusx/item-relationship-service#522]
## Current behaviour
Validation of json-schema passed successfully for SLBAB Payload #2.0.0 and SLBAB json-schema #3.0.0

## Expected behavior

SLBAB Payload in #2.0.0 should not pass validation with SLBAB json-schema #3.0.0 (quantity object is different)

## Steps to reproduce the Bug

Check prepared unit test in: https://github.com/catenax-ng/tx-item-relationship-service/pull/852
Currently test is disabled, but should be enabled in the end.

**Comment by ds-jhartmann** [comment]
Planning 2:
- the lib we use right now does not seem to work. We need to switch to a different one

**Comment by dsmf** [comment]
Pull Request: https://github.com/catenax-ng/tx-item-relationship-service/pull/881

**Comment by mkanal** [comment]
@dsmf @ds-jhartmann @ds-kgassner
INT Tests https://jira.catena-x.net/browse/TRI-767 https://jira.catena-x.net/browse/TRI-1913 https://jira.catena-x.net/browse/TRI-1914 https://jira.catena-x.net/browse/TRI-704 must be executed successful then this is done.

**Comment by mkanal** [comment]
PO acceptance in behalf of @jzbmw. TRI-767 has the eevidence.
