### ISSUE TITLE
REWORK  Transfer to association

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#527]
**As** team
**I want** to transfer all content in a sufficient way to the association
**so that** we conduct transition over in high quality 

## Links 
- child of https://github.com/eclipse-tractusx/sig-release/issues/652
- https://github.com/eclipse-tractusx/item-relationship-service/issues/371
- https://github.com/eclipse-tractusx/item-relationship-service/issues/222

## Hints / Details

- Sources: JIRA Xray, MIRO, Confluence
- Xray: Test Execution files & Feature Files
- Confluence: ??
- Miro: none

## Acceptance Criteria
- [ ] Content to be transferred to association is known 
- [ ] Transfer to association is completed. 
- [ ] Cucumber Feature files are transfered into github

## Out of Scope

- ...

**Comment by jzbmw** [comment]
@jzbmw rework and refactor the 3 Stories named in this Ticket
