### ISSUE TITLE
[POLICY_STORE] Improvements Policy Store input validation

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#528]
**As** product
**I want** to allow only valid parameters in policy store 
**so that** we have the highest level of security

## Link 
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/519
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/561 
- relates  to https://github.com/eclipse-tractusx/item-relationship-service/issues/528 
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/559 
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/560

## Hints / Details

- ...

## Acceptance Criteria
- [ ] Policy Store allows only BPNL numbers (no BPNA / BPNS or input with is not BPNL schema conform)
   - [ ] Registering/Update/Delete policies is only supported for BPNL 
- [ ] Registration of policy with no validUntil failes 
- [ ] Registration of policy with  validUntil in the past failes 
- [ ] Registration of policy with no payload (poilicy) should fail
- [ ] Registering a duplicate policy for same BPNL failes 

## Out of Scope

- ...

**Comment by dsmf** [comment]
what about validating policyid? 
see https://analysiscenter.veracode.com/auth/index.jsp#ViewReportsDetailedReport:47240:1397371:34402311:34371495:34387145:::::4405498 

Improper Output Neutralization for Logs CWE ID 117
- 214 	irs-api-0.0.2-SNAPSHOT-exec.jar/irs-policy-store-0.0.2-SNAPSHOT.jar 	
.../PolicyStoreService.java 117
- 146 	irs-api-0.0.2-SNAPSHOT-exec.jar/irs-policy-store-0.0.2-SNAPSHOT.jar 	
.../PolicyStoreService.java 143

**Comment by dsmf** [comment]
relates to #555

**Comment by dsmf** [comment]
policyId validation e.g. UUID

!!! but we should take into account for the estimation that this requires changing a lot of tests including integration tests !!!

**Comment by dsmf** [comment]
## Outcome

- [x] Policy Store allows only BPNL numbers (no BPNA / BPNS or input with is not BPNL schema conform)
    - [x] Registering policies is only supported for BPNL incl. integration test: https://jira.catena-x.net/browse/TRI-1981
    - [x] Updating policies is only supported for BPNL incl. integration test: https://jira.catena-x.net/browse/TRI-1984 
    - n/a -Deleting policies is only supported for BPNL --> DELETE is by policyId

- [ ] Registration of policy with no validUntil fails
- [ ] Registration of policy with validUntil in the past fails
- [ ] Registration of policy with no payload (poilicy) should fail
- [ ] Registering a duplicate policy for same BPNL fails

Todo:
- [ ] activate integration tests (links see above)

**Comment by dsmf** [comment]
@ds-kgassner -> ready for test

**Comment by ds-kgassner** [comment]
Successfully tested - approved from my side

**Comment by dsmf** [comment]
@mkanal -> ready for PO review

**Comment by mkanal** [comment]
LGFM. PO acceptance in behalf of @jzbmw
