### ISSUE TITLE
[TESTING] Integration E2E Tests for backward compatibility  (Happy + Unhappy Path)

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#529]
**As** team 
**I want** to have test for backward compatibility  of semantic models
**so that** we have a good evidence that irs works 

## Hints / Details

- ...

## Acceptance Criteria
- [x] Tests for different traversal semantic models for major release 3.0.0 SLUAB, SLBAB 
- [x] Tests for different semantic models for major release 2.0.0 PartAsPlanned, SerialPart 3.0.0 etc.
- [x] This covers creating own testdata with new semantic models in future versions with modifications like SerialPart 3.1.0 or 3.2.1 which does not exists right now

## Outcome 
- Cucumber Execution Report https://reports.cucumber.io/reports/93e01d62-6730-495a-9279-2e0902c112c6

## Out of Scope

- ...

**Comment by dsmf** [comment]
PR: 
- Environments-Branch: Semantic models: https://github.com/eclipse-tractusx/item-relationship-service/pull/697
- Test data and tests: https://github.com/eclipse-tractusx/item-relationship-service/pull/702 (DRAFT)
     - [ ] todo: add tests to xray
     - [ ] todo: organize sources to match with xray

**Comment by mkanal** [comment]
Review:
- Please link Tests in Xray to suitable Test Plan for Test Execution. 
-

**Comment by dsmf** [comment]
@mkanal: the list of tests in your comment is missing the following:
https://jira.catena-x.net/browse/TRI-2047

**Comment by dsmf** [comment]
@mkanal: 
>> Please link Tests in Xray to suitable Test Plan for Test Execution.

Since #371 there is no cucumber xray integration anymore, see 
- https://github.com/eclipse-tractusx/item-relationship-service/pull/685/files
- https://github.com/eclipse-tractusx/item-relationship-service/issues/223

![grafik](https://github.com/eclipse-tractusx/item-relationship-service/assets/19529362/8ecfcd04-b497-46b6-964d-99896bda9d00)

**Comment by mkanal** [comment]
Semantic Models like SerialPart are checked against a given schema. Testing agains a new future version will not work in this case. Tests using futureAddedField to simulate a future change in the semantic model are realized only for traversal aspects.

**Comment by mkanal** [comment]
LGFM 
PO acceptance in behalf of @jzbmw
