### ISSUE TITLE
Clean up values.yaml#edc.catalog.acceptedPolicies

### ISSUE THREAD

**Issue by dsmf** [eclipse-tractusx/item-relationship-service#530]
**As** ...,
**I want** clean up the configured default policy,
**so that** obsolete entries are removed.

## Hints / Details

- relates to https://jira.catena-x.net/browse/TRI-1594
- relates to #199

## Acceptance Criteria

- obsolete entries removed from values.yaml#edc.catalog.acceptedPolicies (see comment from planning 2)

## Out of Scope

- ...

**Comment by ds-jhartmann** [comment]
Planning 2:
- remove outdated policies from the default configuration
- adjust the policies of our testdata files in case they do not match anymore

**Comment by dsmf** [comment]
Branch:
- [chore/530-cleanup-acceptedPolicies-configuration](https://github.com/catenax-ng/tx-item-relationship-service/tree/chore/530-cleanup-acceptedPolicies-configuration)

Pull Request: 
- https://github.com/catenax-ng/tx-item-relationship-service/pull/880

**Comment by mkanal** [comment]
@dsmf 
Please have a look here https://github.com/catenax-ng/tx-item-relationship-service/blob/catena-x-environments/charts/irs-environments/dil/values.yaml

**Comment by mkanal** [comment]
@dsmf 
Please have a look here https://github.com/catenax-ng/tx-item-relationship-service/blob/catena-x-environments/charts/irs-environments/dil/values.yaml

**Comment by dsmf** [comment]
https://github.com/catenax-ng/tx-item-relationship-service/pull/887

**Comment by dsmf** [comment]
@mkanal adjusted

**Comment by mkanal** [comment]
@jzbmw 
Ready for review. All topics resolved. Thank you very much.
