### ISSUE TITLE
GET irs/policies should not return BPNLs without policies

### ISSUE THREAD

**Issue by dsmf** [eclipse-tractusx/item-relationship-service#533]
**As** ... ,
**I want** that after DELETE / UPDATE policies each BPN which does not have any policies anymore is removed from the store,
**so that** GET irs/policies does not return BPN's that have no policies.

## Hints / Details

Currently it looks like this:

```
GET irs/policies

{
	"BPNL00000001CRHK": [],
	"BPNL00000003B3NX": [],
	"BPNL00000003B2OM": [
		{
			"validUntil": "2025-12-31T23:59:59.999Z",
			"payload": {
				"@context": {
					"odrl": "http://www.w3.org/ns/odrl/2/"
				},
				"@id": "id-3.0-trace",
				"policy": {
					"policyId": "id-3.0-trace",
					...
				}
			}
		}
	],
	"BPNLTEST12345699": [],
        ...
}
```

Filtering BPN's without policies for GET policies requests is prepared in the following branch: [533-get-policies-filter-out-empty](https://github.com/catenax-ng/tx-item-relationship-service/tree/feat/533-get-policies-filter-out-empty)) **BUT we should do a real cleanup on DELETE / UPDATE policies instead**, so the business partner numbers without policies are removed from the policy store. 

- (?) Also to be clarified: If no policies are defined at all (and there is no BPN with an empty list of policies), the current implementation returns the default policy for get all policies. Is this the expected behavior?
(see PolicyStoreServiceTest.getAllStoredPolicies_whenNoPoliciesAtAll_shouldReturnTheConfiguredDefaultPolicies in branch   [533-get-policies-filter-out-empty](https://github.com/catenax-ng/tx-item-relationship-service/tree/feat/533-get-policies-filter-out-empty) and https://github.com/eclipse-tractusx/item-relationship-service/issues/535)

## Acceptance Criteria

- [x] when DELETE / UPDATE leaves one or more BPN without policies, this must be cleaned up. The BPN must be removed from policy store.
- [x] as a result of this cleanup only BPNLs should be returned that have either been queried specifically or have policies
     - `GET irs/policies` must return only BPN's that have policies.
     - `GET irs/policies?businessPartnerNumbers=<a BPN without policies i.e. not existing in policy store>` must return empty 

## Out of Scope

- ...

**Comment by dsmf** [comment]
## Pull Request
- https://github.com/eclipse-tractusx/item-relationship-service/pull/615

**Comment by dsmf** [comment]
ready for peer review

**Comment by dsmf** [comment]
Hi @mkanal, @ds-kgassner  , ready for test

**Comment by mkanal** [comment]
PO acceptance in behalf of @jzbmw
