### ISSUE TITLE
Fixing current R24.05 setup

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#534]
**As** product
**I want** to re-setup the int environment after reset of portal and bpdm 
**so that** we are able to join the e2e testing phase 

## Acceptance Criteria
- [x] Migration to new "old" keyloak url Token URL: https://centralidp-v2.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token on all environments (e2e, dev, int)
- [x] Conduct Smoke tests for e2e tests 

## Out of Scope

- ...

## Hints / Details
please note that we started to reset the Integration Env. to get ready for the 24.05. E2E tests.
As a result, access to the portal and connected applications will be extremely limited until the E2E tests begin.

I understand that this may have a significant impact on many of you. To mitigate the inconvenience, we enabled a special support function. If you still need/want to perform actions such as EDC communications (version < 0.7 RC1), test runs, etc. using previously used users (both technical and functional), you can proceed by switching your connector and/or app instances to the following Keycloak token URL:

Token URL: https://centralidp-v2.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token

Please note that this IDP instance is our previous INT Keycloak instance, which is now available under a new endpoint path. All user accounts and service accounts are still accessible with your existing credentials.

**Comment by dsmf** [comment]
test on DEV:
- https://jira.catena-x.net/projects/TRI/issues/TRI-1934

**Comment by mkanal** [comment]
![image](https://github.com/eclipse-tractusx/item-relationship-service/assets/100209308/7a173363-e89e-4195-a556-7c184310ce4b)
@dsmf why is the jwkSetUri not updated in vault?

**Comment by ds-jhartmann** [comment]
@mkanal INT was not updated since there was the reset of the entire environment which lead to no data being available anyway. 
The jwkSetUri was not updated because it is no longer in use.
As @dsmf mentioned, the tests were executed successfully, so everything is working as expected again.

**Comment by mkanal** [comment]
Please remove jwkSetUri  as it is not in use.

**Comment by mkanal** [comment]
@ds-jhartmann 
Thank you very much accepted. Works as indended.
