### ISSUE TITLE
Umbrella Helm final touch

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#536]
**As** PO,
**I want** the umbrella helm successfully deployed and and EDC Data Exchange conducted ,
**so that** the umbrella helm can be used in tx community days .

## Hints / Details

- Ingress
- Testdata - IDP ( MIW - User ) 
- Setup Data Provider 

## Acceptance Criteria

- ...

## Out of Scope

- ...

**Comment by ds-jhartmann** [comment]
Umbrella Chart is now working with dataconsumer and dataprovider EDCs. E2E Flow could be tested.
- https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/83
- https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/76

**Comment by mkanal** [comment]
PO approval in behalf of @jzbmw.
