### ISSUE TITLE
Shells not found tombstone has no details

### ISSUE THREAD

**Issue by dsmf** [eclipse-tractusx/item-relationship-service#538]
## Description

Tombstone "Unable to find any of the requested shells" does not contain details why.
(noticed during #405)

## Current behaviour

Tombstone contains no detail why shells not found.

## Expected behavior

Tombstone contains details when shells not found (reason/cause).

## Steps to reproduce the Bug

- Happens if negotiation fails, locally this could be simulated by throwing an exception in EdcSubmodelClientImpl#getEndpointReferencesForAsset.
- Then run IrsWireMockIntegrationTest#shouldStartRecursiveProcesses()

**Comment by dsmf** [comment]
- Propagates exceptions to have more detail in tombstone (using Either and Exception#addSuppressed).
  **Pull Request:** https://github.com/catenax-ng/tx-item-relationship-service/pull/865
    - this is still DRAFT, automated test still missing

**Comment by ds-jhartmann** [comment]
How to test:
- Case: Job started with a non-existing globalAssetId ➡️ Tombstone should mention that Digital Twin could not be found
- Case: Policy of DTR offer does not match the allowed Policy ➡️ Tombstone should mention that policy does not match
- Case: EDC Discovery Does not return a EDC endpoint ➡️ Tombstone should mention that EDC Endpoints could be discovered
- Case: EDC Error ➡️ Tombstone should mention EDC error

**Comment by dsmf** [comment]
one cucumber test fails due to newly added field rootCauses:
https://reports.cucumber.io/reports/2be1ffb2-e72c-4cf5-ac5e-8d489ed9f1eb

PR for exclusion (does not change test logic):
https://github.com/eclipse-tractusx/item-relationship-service/pull/800

**Comment by dsmf** [comment]
We still lack some details, because we do not go deep enough to get the real root causes, maybe we should use  `ExceptionUtils.getRootCause(e);` from Apache Commons to extract the root causes.

**Comment by ds-kgassner** [comment]
Successfully tested: 
- Case: Job started with a non-existing globalAssetId 
- Case: Policy of DTR offer does not match the allowed Policy

**Comment by mkanal** [comment]
@ds-jhartmann and @ds-kgassner 
Are there any int or other automatic tests created for these scenarions? 
- Case: Job started with a non-existing globalAssetId ➡️ Tombstone should mention that Digital Twin could not be found
- Case: Policy of DTR offer does not match the allowed Policy ➡️ Tombstone should mention that policy does not match
- Case: EDC Discovery Does not return a EDC endpoint ➡️ Tombstone should mention that EDC Endpoints could be discovered
- Case: EDC Error ➡️ Tombstone should mention EDC error
- Case: Job started with a non-existing globalAssetId
- Case: Policy of DTR offer does not match the allowed Policy

**Comment by mkanal** [comment]
After alignment with @ds-jhartmann  the bug is covered with mock tests on unit level. 
LGFM PO acceptance in behalf of @ds-jhartmann.

**Comment by dsmf** [comment]
Integration Test see IrsWiremockIntegrationTest (see all tests with asserts on ` actualTombstone.getProcessingError().getRootCauses()`)
