### ISSUE TITLE
Setup environments after reset of Integration Env. to get ready for the 24.05. E2E tests.

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#539]
**As** product
**I want** to re-setup the int environment after reset of portal and bpdm 
**so that** we are able to join the e2e testing phase 

## Links 
- related to https://github.com/eclipse-tractusx/traceability-foss/issues/855

## Acceptance Criteria
- [x] Setup companies IRS
- [x] Register connectors 
- [x] Conduct Smoke tests for e2e tests 

## Out of Scope

- ...

## Hints / Details
please note that we started to reset the Integration Env. to get ready for the 24.05. E2E tests.
As a result, access to the portal and connected applications will be extremely limited until the E2E tests begin.

I understand that this may have a significant impact on many of you. To mitigate the inconvenience, we enabled a special support function. If you still need/want to perform actions such as EDC communications (version < 0.7 RC1), test runs, etc. using previously used users (both technical and functional), you can proceed by switching your connector and/or app instances to the following Keycloak token URL:

Please note that this IDP instance is our previous INT Keycloak instance, which is now available under a new endpoint path. All user accounts and service accounts are still accessible with your existing credentials. 

# Outcome 

- Created company "doubleSlash Net Business GmbH" as former Trace-X A with BPNL

![Image](https://github.com/eclipse-tractusx/item-relationship-service/assets/100209308/b9397de5-7d6d-4d04-8a34-23073f6bd9b5)

- Created company "BMW" as former IRS Customer with BPNL

![Image](https://github.com/eclipse-tractusx/item-relationship-service/assets/100209308/fdc9d7af-24a3-47bb-a1b9-166c5db11eed)

- Created company "Trace-X" as former Trace-X B with BPNL

![Image](https://github.com/eclipse-tractusx/item-relationship-service/assets/100209308/29cd514b-1c67-4f84-977b-40d8fb5916f4)

**Comment by jzbmw** [comment]
BLOCKED: DIM, DID Service must be available. Portal Accounts must be available.

**Comment by mkanal** [comment]
Blocked because registration of company in portal is not possible right now.

**Comment by mkanal** [comment]
@jzbmw ready to review
