### ISSUE TITLE
Incomprehensible error message of api parameter direction

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#567]
## Current behaviour
- Error message in misleading
- As "upwards" is not correct this fails 

## Expected behavior
- Reasonable error message
- User should now that "upwards" is not a valid paramter this should be "upward"

## Steps to reproduce the Bug
`
````
{
	"key": {
		"globalAssetId": "urn:uuid:c6d2d642-a055-4ddf-87e3-1a3b02c689e3",
		"bpn": "BPNL00000000BJTL"
	},
"direction" :  "upwards",
"lookupBPNs" : true
}

````

![Image](https://github.com/eclipse-tractusx/item-relationship-service/assets/100209308/f658c6b5-2e15-4e7f-b144-23bb9a56cb2f)

**Comment by dsmf** [comment]
PR: https://github.com/catenax-ng/tx-item-relationship-service/pull/906

**Comment by dsmf** [comment]
@mkanal , @ds-kgassner -> ready for test

**Comment by ds-kgassner** [comment]
successfully tested - approved from my side

**Comment by dsmf** [comment]
@jzbmw ready for PO-review
