### ISSUE TITLE
IRS Job hung in case BPDM Service is not available and lookupBPNs = true

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#568]
## Acceptance criteria 
- [ ] Set bpdm lookup as deprecated in API
- [ ] Return empty bpns [] over API endpoint 
- [ ] Remove code for BPDM lookup 
- [ ] Remove documentation 
- [ ] Remove bpdm Lookup from INT and e2e tests  

## Link 
- related to  https://github.com/eclipse-tractusx/traceability-foss/issues/901
- related to  https://github.com/eclipse-tractusx/traceability-foss/issues/902
- related to https://github.com/eclipse-tractusx/item-relationship-service/issues/568

## Current behaviour
- job hungs if BPDM service is not available

## Expected behavior
- job response even if bpdm service is not present with correct error message

## Steps to reproduce the Bug
- "lookupBPNs": true 
- BPDM is not available 
````
{
	"aspects": [
		"urn:samm:io.catenax.serial_part:3.0.0#SerialPart",                          
"urn:samm:io.catenax.single_level_bom_as_built:3.0.0#SingleLevelBomAsBuilt", 
"urn:samm:io.catenax.just_in_sequence_part:3.0.0#JustInSequencePart", 
"urn:samm:io.catenax.batch:3.0.0#Batch"
	],
	"key": {
		"globalAssetId": urn:uuid:8724338c-5c85-4c34-91eb-e2735d58fb0d
		"bpn": BPNL00000003AVTH
	},
	"collectAspects": true,
	"lookupBPNs" : true,
	"depth" :100,
	"direction" : "downward"
}
````

**Comment by ds-jhartmann** [comment]
Planning 2:
might solve the issue with long cucumber integration tests https://github.com/eclipse-tractusx/item-relationship-service/issues/574

**Comment by dsmf** [comment]
https://github.com/catenax-ng/tx-item-relationship-service/pull/907
feat(impl):[#568] insomnia collection update --> approved and merged

**Comment by dsmf** [comment]
https://github.com/catenax-ng/tx-item-relationship-service/pull/905 feat(impl):[#568] remove bpdm lookup --> approved

**Comment by dsmf** [comment]
Eclipse TX synch PR: 
https://github.com/eclipse-tractusx/item-relationship-service/pull/583

**Comment by dsmf** [comment]
@ds-ext-kmassalski  looks like there are some cucumber tests that need to be fixed, see screenshot I sent you via teams

**Comment by mkanal** [comment]
@ds-ext-kmassalski 
- **And lookupBPNs "false** still occurs in Cucumber Tests 
- Was insomnia collection updated?

**Comment by mkanal** [comment]
PO acceptance in behalf of @jzbmw. 
Flag was removed from insomnia / Cucumber tests and jobResponse.
