### ISSUE TITLE
Manually fix test dataset and reupload to DEV to continue with e2e test phase

### ISSUE THREAD

**Issue by ds-ext-kmassalski** [eclipse-tractusx/item-relationship-service#569]
## Hints / Details

- official test datasets contains submodel payload that do not match json-schema from SemanticsHub
- fix manually payload to make IRS able to collect submodels
- reports bugs to appropriate teams

## Acceptance Criteria

- Fixed dataset uploaded to DEV
- IRS is able to collect and validate submodel payloads

**Comment by mkanal** [comment]
@jzbmw fixed and ready for review
