### ISSUE TITLE
Tavern Tests: Fix Tavern ESS Tests with available aspects

### ISSUE THREAD

**Issue by ds-kgassner** [eclipse-tractusx/item-relationship-service#579]
**As a tester / developer,
**I want to fix the aspects for the Tavern ESS Test for the Dev environment,
**so that our tests operate without errors .

## Hints / Details

At the moment, the IRS ESS Tavern Tests fail because the handed over aspects do not match the available aspects.
It is about following aspects:
'[PartSiteInformationAsPlanned, PartAsPlanned]'

Test execution: https://jira.catena-x.net/browse/TRI-1963 e.g. [Make sure investigation job with valid globalAssetId and BPN is processed correctly]

## Acceptance Criteria

- [ ] ESS INT tests are adapted to the new test dataset.
- [ ] ESS INT tests are adapted to the new release.

## Out of Scope

- ...

**Comment by ds-jhartmann** [comment]
Fixed ESS investigation completion https://github.com/eclipse-tractusx/item-relationship-service/pull/656

**Comment by ds-jhartmann** [comment]
ready for testing @ds-kgassner

**Comment by mkanal** [comment]
https://jira.catena-x.net/browse/TRI-910
LGFM. PO acceptance in behalf of @jzbmw
