### ISSUE TITLE
Prepare reduced fixed dataset and upload to DEV to continue e2e tests

### ISSUE THREAD

**Issue by ds-ext-kmassalski** [eclipse-tractusx/item-relationship-service#585]
## Hints / Details

- the Testdata set was updated see https://jira.catena-x.net/browse/TDG-45
and https://jira.catena-x.net/browse/TDG-44
- Dataset can be found here: https://jira.catena-x.net/secure/attachment/24355/24355_CX_Testdata_V1.7.0_Partinstance.zip
- Prepare reduced set of data and then upload fixed dataset to DEV to continue with e2e test phase

## Acceptance Criteria

- DEV env contains newest reduced and fixed dataset

**Comment by mkanal** [comment]
PO acceptance in behalf of @jzbmw testdata is uploaded and ready to test.
