### ISSUE TITLE
[TESTING] Cucumber testing supports check of tombstones

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#595]
**As** tester
**I want** to check against tombstones collections inside cucumber tests
**so that** to check the result of tests of unhappy path 

## Hints / Details
- And I check, if "tombstones" are equal to "TRI-XX-expected-tombstones.json"

## Acceptance Criteria
- [x] Cucumber tests allows check of defined tombstone payload (analogous to relationships and submodels)

## Out of Scope

- ...

**Comment by dsmf** [comment]
usage example:
 
595-expected-tombstones.json (not checked in):
```
{
  "tombstones": [
    {
      "catenaXId": "urn:uuid:aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
      "endpointURL": null,
      "businessPartnerNumber": null,
      "processingError": {
        "processStep": "DigitalTwinRequest",
        "errorDetail": "Unable to find any of the requested shells",
        "lastAttempt": "2024-05-17T15:40:38.8134781Z",
        "retryCounter": 3
      },
      "policy": null
    }
  ]
}
```

and 

```
Feature: Default

  Background:
    Given the IRS URL "http://localhost:8080/"
    And the admin user api key

    Given the IRS URL "https://irs.dev.demo.catena-x.net"
    And the admin user api key    

  Scenario: test tombstone
    Given I register an IRS job for globalAssetId "urn:uuid:aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa" and BPN "BPNL00000000TEST"
    And aspects :
      | urn:samm:io.catenax.shared.part_site_information_as_built:1.0.0#PartSiteInformationAsBuilt |
    And collectAspects "true"
    And depth 1
    And bomLifecycle "asBuilt"
    And direction "downward"
    When I get the job-id
    Then I check, if the job has status "COMPLETED" within 5 minutes
    And I check, if number of "tombstones" equals to "summary/asyncFetchedItems/failed"
    And I check, if "tombstones" are equal to "595-expected-tombstones.json"
```

**Comment by ds-jhartmann** [comment]
Added the option to check for expected tombstones in https://github.com/eclipse-tractusx/item-relationship-service/pull/657

**Comment by ds-jhartmann** [comment]
Ready for testing @ds-kgassner

**Comment by ds-jhartmann** [comment]
Added test TRI-2035 and expected tombstone file in https://github.com/eclipse-tractusx/item-relationship-service/pull/676

**Comment by ds-jhartmann** [comment]
Tombstone Cucumber Test executed successfully 
![image](https://github.com/eclipse-tractusx/item-relationship-service/assets/57985712/6dc4392d-ba06-4140-b8ca-59a27e66e94e)

**Comment by mkanal** [comment]
LGFM: PO acceptance in behalf of @jzbmw
