### ISSUE TITLE
TRG 1.04 editable static files

### ISSUE THREAD

**Issue by ds-mwesener** [eclipse-tractusx/item-relationship-service#618]
Please convert: AAS_Access_v3_Architecture.jpg with a proper converter like mermaid.

**Comment by dsmf** [comment]
## Outcome
- branch: https://github.com/catenax-ng/tx-item-relationship-service/tree/chore/618-TRG-1-04-editable-static-files
- direct link to section: https://github.com/catenax-ng/tx-item-relationship-service/blob/chore/618-TRG-1-04-editable-static-files/docs/concept/%23438-investigation-dDTR-api-endpoints/%23438-investigation-dDTR-api-endpoints.md#aas_access_v3_architecture
- Pull Request: https://github.com/eclipse-tractusx/item-relationship-service/pull/640
- TODO Synch PR Eclipse TX -> Catena

**Comment by ds-mwesener** [comment]
Approved.

**Comment by mkanal** [comment]
PO acceptance in behalf of @jzbmw
