### ISSUE TITLE
[POLICY_STORE] Add filter, sorting, pagination for GET endpoints

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#639]
**As** business app Trace-X 
**I want** use  filter, sorting, pagination for GET endpoints  
**so that** we could visualize the data in a sufficient way 

## Links 
-  Relates to https://github.com/eclipse-tractusx/traceability-foss/issues/969
-  relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/750

## Hints / Details

- ...

## Acceptance Criteria
- [x] policy store GET endpoints supporting **GET /irs/policies**
  - [ ] filtering on attributes [BPN, validUntil, policyId, createdOn, action,] 
      - [ ]  For filtering on attribute action  first permission entry in array is used 
  - [ ] sorting on attributes [BPN, validUntil, policyId, createdOn, action,] asc, desc, default sorting is BPN asc
      - [ ]  For sorting on attribute action  first permission entry in array is used 
  - [ ] pagination  min 1 / max 1000 
- [ ] Update Insomnia 
- [ ] Update documentation 
- [ ] Update tests 

## Out of Scope
- sorting on attributes [constraint,] 
- filter on attribute [constraint]

**Comment by dsmf** [comment]
relates to #563

**Comment by dsmf** [comment]
@mkanal: 
The current implementation GET /irs/policies returns a map of policies, not a list. How should the paging work here? 

```
{
	"BPNL1234567890AB": [
		{
			"validUntil": "2025-12-12T23:59:59.999Z",
			"payload": {
				"@context": {
					"odrl": "http://www.w3.org/ns/odrl/2/"
				},
				"@id": "test-policy",
				"policy": {
					"policyId": "test-policy",
					"createdOn": "2024-06-21T09:27:00.879555167Z",
					"validUntil": "2025-12-12T23:59:59.999Z",
					"permissions": [
						...
					]
				}
			}
		},
		{
			"validUntil": "2025-12-12T23:59:59.999Z",
			"payload": {
				"@context": {
					"odrl": "http://www.w3.org/ns/odrl/2/"
				},
				"@id": "policy461",
				"policy": {
					"policyId": "policy461",
					"createdOn": "2024-06-21T16:55:53.978335099Z",
					"validUntil": "2025-12-12T23:59:59.999Z",
					"permissions": [
						...
					]
				}
			}
		},
		{
			"validUntil": "2025-12-12T23:59:59.999Z",
			"payload": {
				"@context": {
					"odrl": "http://www.w3.org/ns/odrl/2/"
				},
				"@id": "policy462",
				"policy": {
					"policyId": "policy462",
					"createdOn": "2024-06-26T07:41:39.225535365Z",
					"validUntil": "2025-12-12T23:59:59.999Z",
					"permissions": [
						...
					]
				}
			}
		},
		{
			"validUntil": "3333-11-11T11:11:11.111Z",
			"payload": {
				"@context": {
					"odrl": "http://www.w3.org/ns/odrl/2/"
				},
				"@id": "aaaaaaaa-aaaa-aaaa-aaaa-333333333333",
				"policy": {
					"policyId": "aaaaaaaa-aaaa-aaaa-aaaa-333333333333",
					"createdOn": "2024-06-29T23:53:45.121508739Z",
					"validUntil": "3333-11-11T11:11:11.111Z",
					"permissions": [
						...
					]
				}
			}
		},
		{
			"validUntil": "4444-11-11T11:11:11.111Z",
			"payload": {
				"@context": {
					"odrl": "http://www.w3.org/ns/odrl/2/"
				},
				"@id": "aaaaaaaa-aaaa-aaaa-aaaa-444444444444",
				"policy": {
					"policyId": "aaaaaaaa-aaaa-aaaa-aaaa-444444444444",
					"createdOn": "2024-06-29T23:53:45.429472715Z",
					"validUntil": "4444-11-11T11:11:11.111Z",
					"permissions": [
						...
					]
				}
			}
		}
	],
	"BPNL1234567890CD": [
		{
			"validUntil": "4444-11-11T11:11:11.111Z",
			"payload": {
				"@context": {
					"odrl": "http://www.w3.org/ns/odrl/2/"
				},
				"@id": "aaaaaaaa-aaaa-aaaa-aaaa-444444444444",
				"policy": {
					"policyId": "aaaaaaaa-aaaa-aaaa-aaaa-444444444444",
					"createdOn": "2024-06-29T23:53:45.429472715Z",
					"validUntil": "4444-11-11T11:11:11.111Z",
					"permissions": [
						...
					]
				}
			}
		},
		{
			"validUntil": "5555-11-11T11:11:11.111Z",
			"payload": {
				"@context": {
					"odrl": "http://www.w3.org/ns/odrl/2/"
				},
				"@id": "aaaaaaaa-aaaa-aaaa-aaaa-555555555555",
				"policy": {
					"policyId": "aaaaaaaa-aaaa-aaaa-aaaa-555555555555",
					"createdOn": "2024-06-29T23:53:46.062423628Z",
					"validUntil": "5555-11-11T11:11:11.111Z",
					"permissions": [
						...
					]
				}
			}
		},
		{
			"validUntil": "6666-11-11T11:11:11.111Z",
			"payload": {
				"@context": {
					"odrl": "http://www.w3.org/ns/odrl/2/"
				},
				"@id": "aaaaaaaa-aaaa-aaaa-aaaa-666666666666",
				"policy": {
					"policyId": "aaaaaaaa-aaaa-aaaa-aaaa-666666666666",
					"createdOn": "2024-06-29T23:53:46.371117205Z",
					"validUntil": "6666-11-11T11:11:11.111Z",
					"permissions": [
						...
					]
				}
			}
		}
	]
}
```

**Comment by dsmf** [comment]
discussed with @ds-mwesener: 
we add bpn on the same level as validUntil and return a paged list instead of map

**Comment by dsmf** [comment]
@mkanal: @ds-mwesener said they need multi-sort and multi-filter (with flexible sort operators). Single-sort is no problem. Maybe multi-sort can be implemented within the estimation too, but multi-filter goes far beyond the acceptance criteria in this story and cannot be implemented within the estimation.

**Comment by mkanal** [comment]
@dsmf please include multi-sort within this story. I will create a story with multi-filter.

**Comment by dsmf** [comment]
draft PR: https://github.com/eclipse-tractusx/item-relationship-service/pull/754

**Comment by dsmf** [comment]
PRs:
https://github.com/eclipse-tractusx/item-relationship-service/pulls?q=is%3Apr+is%3Aopen%2Cclosed+title%3A639+

**Comment by dsmf** [comment]
## Outcome:

### GET /irs/policies/paged

#### Pagination
- [x] pagination with min 1 / max 1000 using Spring's standard pagination structures

#### Filtering
- [x] multi-filter possible `&search=...&search=...`
- [x] filter by BPN `search=bpn,[EQUALS|STARTS_WITH],<value>`
- [x] filter by policyId `search=policyId,[EQUALS|STARTS_WITH],<value>`
- [x] filter by action (first one in permission list is used for filtering), `search=action,[EQUALS],[use|access]`
- filter by createdOn (will be implemented in #750)
- filter by validUntil (will be implemented in #750)

#### Sorting
- [x] sort direction asc, desc
- [x] default sorting is BPN asc
- [x] multi-sort possible `sort=...&sort=...
- [x] sort by BPN `sort=bpn,[asc|desc]`
- [x] sort by policyId `sort=policyId,[asc|desc]`
- [x] sort by action (first one in permission list is used for sorting) `sort=action,[asc|desc]`
- [x] sort by createdOn `sort=createdOn,[asc|desc]`
- [x] sort by validUntil `sort=validUntil,[asc|desc]`    

#### Tests
- [x] Unit tests for the new code paging, sorting, filtering, mainly see PolicyPagingServiceTest

_Hint: Integration tests can stay as they are temporarily because the old endpoint without paging is not removed in order to keep backward compatibility until the frontend is adapted._

#### Documentation
- [x] Update Insomnia
- [x] Update documentation


## Pull Request
- Impementation: https://github.com/eclipse-tractusx/item-relationship-service/pull/754
- Documentation: https://github.com/eclipse-tractusx/item-relationship-service/pull/766
- Insomnia Collection Update: https://github.com/eclipse-tractusx/item-relationship-service/pull/767

- https://irs.dev.demo.catena-x.net/api/swagger-ui/index.html

**Comment by mkanal** [comment]
@dsmf 
- Description of GET /irs/policies and /irs/policies/paged mismatch  please correct 
- "Fetch a page of policies with options to filter and sort." Please update regarding description of GET /irs/policies which provides similar results with the only difference that it is not sorted and filterable 
- Please add to description timeformat accepted and which Operator could be used for which datatype [EQUALS|STARTS_WITH|BEFORE_LOCAL_DATE|AFTER_LOCAL_DATE] 

![image](https://github.com/user-attachments/assets/62597a58-1502-418e-9b58-ae629c775c57)

**Comment by mkanal** [comment]
@dsmf 
500 internal server error 
{{IRS_HOST}}/irs/policies/paged?search=validUntil,BEFORE_LOCAL_DATE,3333-11-11T11:11:11.111Z

![image](https://github.com/user-attachments/assets/d3a31cfc-39e5-4182-b7ba-61009efcc5be)

**Comment by dsmf** [comment]
Thanks, @mkanal. I'll add some handling for the date format exeption to map to a BAD_REQUEST with a more user friendly message instead.

**Comment by dsmf** [comment]
## PR for documentation improvement
https://github.com/eclipse-tractusx/item-relationship-service/pull/830

**Comment by dsmf** [comment]
## PR for date format exception handling
https://github.com/eclipse-tractusx/item-relationship-service/pull/831

**Comment by dsmf** [comment]
## PR for improvement of IrsApplicationTests.generatedOpenApiMatchesContract
(because I noticed during documentation improvement above that the ignores seem to be obsolete). 
https://github.com/eclipse-tractusx/item-relationship-service/pull/831

**Comment by dsmf** [comment]
## PR to support any ISO date in date search filters for createdOn and validUntil
https://github.com/eclipse-tractusx/item-relationship-service/pull/844

**Comment by dsmf** [comment]
## PR for deprecation note for old endpoint `GET /irs/policies`

https://github.com/eclipse-tractusx/item-relationship-service/pull/845

**Comment by dsmf** [comment]
deployed to DEV:
- deprecation note for old endpoint GET /irs/policies
- date filters support any ISO date now, not just yyyy-MM-dd

![grafik](https://github.com/user-attachments/assets/0668801e-22f5-41bb-91f2-48603993d2fb)
