### ISSUE TITLE
Adjustments to the EDC policy in EDC Client library

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#648]
## Link 
- relates to https://github.com/eclipse-tractusx/traceability-foss/issues/978
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/648

## Current behaviour
- Policy #Action: Policy ordl:action is capital letter 

## Expected behavior
- [x] Policy #Action: Policy ordl:action is small letters "use" 
- [x] Add all values in expanded mode (e.g. instead version -> https://w3id.org/.../#version)
- [x] Use correct dct:type: for registry 
- [x] Use defined ontology version 3.0  
- [x] Define  namespaces in context 
````
 @context: { 
   "@vocab" : "https://w3id.org/edc/v0.0.1/ns/",
   "edc": "https://w3id.org/edc/v0.0.1/ns/",
   "cx-policy": "https://w3id.org/catenax/policy/",
   "ordl": "https://w3id.org/ns/ordl/2/",
}
````
![GEC_E2E_Testing](https://github.com/eclipse-tractusx/item-relationship-service/assets/100209308/e2b1dfd6-c23e-4ce7-94d3-3ab8aad17f86)

## Hints
- [x] Add all values in expanded mode (e.g. instead version -> https://w3id.org/.../#version)
- [x] Use correct dct:type: for notifications:
- e.g. "dct:type": {
                "@id": "https://w3id.org/catenax/taxonomy#UpdateQualityAlertNotification"
            }

**Comment by ds-jhartmann** [comment]
ready for testing @ds-kgassner

**Comment by ds-kgassner** [comment]
successfully tested - approved from side.

**Comment by mkanal** [comment]
LGFM. PO acceptance in behalf of @jzbmw
