### ISSUE TITLE
IRS Policy Validation accepts subset of AND constraint

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/item-relationship-service#649]
## Current behaviour

When IRS accepted policy has a AND constraint with 2 constraints and the EDC offer policy has a AND constraint with 1 constraint, IRS accepts the Policy if one of the IRS accepted policies matches the EDC offer policy AND constraint.

## Expected behavior
- [ ] IRS accepted Policies have to match exactly the EDC offer policy.

## Steps to reproduce the Bug

- [x] IRS accepted Policy with AND constraint A1 and A2 
- [x] EDC offer with AND constraint A1
- [ ] IRS job with contract negotiation.
     - [ ]  actual: Negotiation is started with IRS accepting the policy
     - [ ]  expected: Negotiation is aborted with IRS not accepting the policy because constraint A2 is missing in EDC offer

**Comment by ds-jhartmann** [comment]
## Planning 2
Check for policies is done here https://github.com/eclipse-tractusx/item-relationship-service/blob/72b03963cce3895d75e6b651b0b405195dd716d3/irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/policy/ConstraintCheckerService.java#L46-L58

Make sure that and constraints match for all constraints

**Comment by dsmf** [comment]
@ds-jhartmann: shouldn't it be the other way around: andConstraint one constraint more than acceptedPolicy?
```
        final AndConstraint andConstraint = createAndConstraint(
                List.of(createAtomicConstraint(TestConstants.FRAMEWORK_AGREEMENT_TRACEABILITY,
                                TestConstants.STATUS_ACTIVE),
                        createAtomicConstraint(TestConstants.MEMBERSHIP, TestConstants.STATUS_ACTIVE),
                        createAtomicConstraint(TestConstants.PURPOSE, TestConstants.ID_3_1_TRACE)));

        final Policy acceptedPolicy = createPolicyWithAndConstraint(
                List.of(new Operand(TestConstants.FRAMEWORK_AGREEMENT_TRACEABILITY, TestConstants.STATUS_ACTIVE),
                        new Operand(TestConstants.PURPOSE, TestConstants.ID_3_1_TRACE)));

        boolean result = cut.hasAllConstraint(acceptedPolicy, List.of(andConstraint));

        assertThat(result).isFalse();
```

**Comment by ds-jhartmann** [comment]
> @ds-jhartmann: shouldn't it be the other way around: andConstraint one constraint more than acceptedPolicy?
> 
Oh, you're right. The bug describes your behavior. However, the Test example I provided should also fail, since the Policy does not match exactly

**Comment by dsmf** [comment]
## Outcome

- AND does not allow subsets in any direction anymore (list of constraints must be same size and all must match) -> see corrections in ConstraintCheckerService.isSameAs and ConstraintCheckerServiceTest.SubsetAndTests
- fixed tests in PolicyCheckerServiceTest and removed one obsolete test concerning XOne (which we do not support)
- improved readability of tests

## PR

**Comment by ds-kgassner** [comment]
Successfully tested:
Starting Point: EDC has 2 constraints

-     IRS accepted policy has 3 constraints: syntax and value match EDC policy
-     IRS accepted policy has 2 constraints: syntax and value match EDC policy
-     IRS accepted policy has 2 constraints: syntax does not match EDC policy
-     IRC accepted policy has 2 constraints: value does not match EDC policy

**Comment by mkanal** [comment]
Testscenario:
- Create a policy with an additional constraint to the "default" policy.  

![image](https://github.com/user-attachments/assets/b242c028-feb9-41f6-a18a-bdc3ea7b05af)

**Comment by mkanal** [comment]
LGFM. PO acceptance in behalf of @jzbmw .
