### ISSUE TITLE
[RELEASE24.8] Release Checks R24.8

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#719]
**As** team
**I want** to fulfill release checks successfully 
**so that** product is official released and part of release 24.8. 

## Link 
- relates to https://github.com/eclipse-tractusx/sig-release/issues/740
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/817

## Hints / Details

- ...

## Acceptance Criteria
- [x] Release checks R24.8
- [x] ~TRG https://eclipse-tractusx.github.io/docs/release/trg-0/trg-1-08 is implemented~ 
- [x] Participation in E2E test phase 
- [x] Participation in E2E phase and kickoff 

### Security Checks
_There are no Consortium checks for Rel 24.08 and following. Everything is described in the TRG. (Security is TRG 08) 
It is the task of the committers to check this if necessary_

- [x]  ~**Threat Modeling Analysis** passed~
  - [x] trg-8-01 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-01
  - [x] trg-8-02 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-02
  - [x] trg-8-03 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03
  - [x] trg-8-04 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-04

## Out of Scope

- ...

**Comment by mkanal** [comment]
AC removed as TRG https://eclipse-tractusx.github.io/docs/release/trg-0/trg-1-08 is not present any more.

**Comment by mkanal** [comment]
![image](https://github.com/user-attachments/assets/ade33f47-84b1-47c3-a54b-30f86485136e)

**Comment by ds-kgassner** [comment]
E2E tests successfully completed.
![grafik](https://github.com/user-attachments/assets/838b0695-1545-4cbc-a675-d2f6c58f8aa9)

**Comment by ds-jhartmann** [comment]
Reqesting final approval @mkanal
