### ISSUE TITLE
PolicyAPI - Default policy collection is shown in GET /irs/policies

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#734]
**As** Trace-X
**I want**  default policy to be shown in GET /irs/policies
**so that** default policy is always visible 

## Hints / Details

- ...

## Acceptance Criteria

- [x] Default policy is always listed in GET /irs/policies 
- [x] Filter for default policy is supported  GET /irs/policies?businessPartnerNumbers=?default
- [x] Integration Tests 
- [x] Documentation in Arc42 

## Testing 
- [x] Show default policy after adding policy for BPN
   - [x] Create default policy, add policy with BPN 
   - [x]  Call Endpoint GET /irs/policies without parameter
   - [x]  Expected result: Default policy is listed

## Out of Scope

- ...

**Comment by mkanal** [comment]
If no BPNL is used the default policy is overridden only in this case when no BPNL is given.

**Comment by ds-jhartmann** [comment]
## Planning 2
- define a process on how to create/update the default policy which allows to filter for the default policy

**Comment by dsmf** [comment]
if in db no default policy the configured default needs to be returned

**Comment by dsmf** [comment]
draft PR https://github.com/eclipse-tractusx/item-relationship-service/pull/791

**Comment by ds-kgassner** [comment]
successfully tested

**Comment by mkanal** [comment]
@dsmf 
500 error in case of update default policy 


![image](https://github.com/user-attachments/assets/3ed4c741-f26e-4e97-8a03-ccfc3fb620cd)

**Comment by dsmf** [comment]
@mkanal 
Default Policy Handling is no component. It has to do with configuration. Therefore I don't see what we should change in the arc42 configuration. How to configure default policies is described in 
https://eclipse-tractusx.github.io/item-relationship-service/docs/administration/administration-guide.html#_helm_configuration_irs_values_yaml

**Comment by mkanal** [comment]
@dsmf Documentation in Arc42 is a AC criteria. Please document the api in the Building block view. Thx.

**Comment by mkanal** [comment]
LGFM PO acceptance in behalf of @jzbmw . https://github.com/eclipse-tractusx/item-relationship-service/pull/835 provides solution. Arc42 documentation for policy store api will be part of another story.
