### ISSUE TITLE
Deploy running product 24.08 on Association infrastructure (int.catena-x.net)

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#748]
**As** product
**I want** to deploy the product on new infrastructure
**so that** we are able to participate in release 24.8

## Link 
- relates to https://github.com/eclipse-tractusx/sig-infra/issues/515 
- relates to https://github.com/eclipse-tractusx/sig-infra/issues/516

## Hints / Details
- ArgocCD https://argocd.int.catena-x.net 
- Vault https://vault.core.catena-x.net 
- Test data has to be created by team. BPNs have to match the Trace-X companies for proper EDC discovery

## Acceptance Criteria
- [x] Product is deployed and running on association infrastructure (Integraqted with shared services on INT)
- [x] Technical Users for discovery and semantic hub are created
- [x] EDC is registered in Portal and DIM credentials are requested
- [x] Test data is defined and uploaded to Trace-X instances
- [x] Product is integrated with shared products' infrastructure (portal, idp, semantic hub, discovery finder, etc)
- [x] Smoke Tests conducted
- [x] Full E2E Tests conducted on https://argocd.int.catena-x.net 

## Out of Scope

- ...
## Prerequisites
 - [x] Portal is available for EDC registration and Technical User creation
 - [x] Discovery Finder is available
 - [x] Central-IDP is available
 - [x] Semantic Hub is available (alternative: provide semantic models through IRS config)

**Comment by ds-jhartmann** [comment]
IRS Deployed to association Environment:
IRS: https://irs.int.catena-x.net
BPN: BPNL000000000EVQ
IRS_EDC: https://irs-consumer-controlplane.int.catena-x.net

**Comment by ds-jhartmann** [comment]
E2E tests successfully executed https://github.com/eclipse-tractusx/item-relationship-service/actions/runs/10109910486
https://catena-x.atlassian.net/browse/CXTM-926

**Comment by ds-kgassner** [comment]
E2E tests successfully completed.
![grafik](https://github.com/user-attachments/assets/2e5792cf-33c0-44c3-889d-dacea081a253)

**Comment by ds-jhartmann** [comment]
Reqesting final approval @mkanal
