### ISSUE TITLE
[POLICY_STORE]  Multi-Filter support for API endpoint GET /irs/policies

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#750]
**As** api endpoint consumer
**I want** filter for multiple columns at one time
**so that** I am able to filter policies based on my specific request

## Links
- relates to https://github.com/eclipse-tractusx/traceability-foss/issues/969

## Hints / Details
- API endpoint GET /irs/policies supports no filter support attribute

## Acceptance Criteria
- [x] Enable multiple filter support on all attributes with AND combination 
   - [x] Datatype: String supports Operator equals 
   - [x] Datatype: Date supports Operator (Date Range, Date from, Date to)
- [x] Add autocompletion for district values [startsWith A%] (limited by 100 entries)
- [ ] ~Convert GET to POST endpoint POST /policies/paged~

````
 "searchCriteria": {
        "filter": [
            "channel,EQUAL,SENDER,AND"
        ]
    }
````

## Out of Scope
- [x] Multi filter support on column "Constraints" 
- [x] Enable multiple filter support on all attributes with OR combination - results with NotSupported Exception

**Comment by mkanal** [comment]
@dsmf Please clarify if OR combination is really needed and currently supported by Trace-X.

**Comment by dsmf** [comment]
Hi @mkanal, just talked to @ds-mwesener:
- "OR" is not needed, all criteria are connected with "AND" (as already implemented in #639)
- the date filtering needs to be discussed from a business point of view: should there be a separate date range filter for createdOn and validUntil or should there be one date range query that returns all policies where both createdOn and validFrom are inside the given range? something like `search=createdOn,BETWEEN,<dateFrom>_<dateTo>&search=validUntil,BETWEEN,<dateFrom>_<dateTo>` or should there rather be a virtual sort field called validity `search=validity,BETWEEN,<dateFrom>_<dateTo>` which matches all policies where both createdOn and validFrom are in the given range?
- but we need a separate autocomplete endpoint that only returns distinct results for the requested field
- and we need a GET /policies/{policyId} for getting the policy detail by policyId (probably with a list of associated BPNs). The paging endpoint works differently here as it returns the same policy multiple times - one for each associated BPN
- and #750 (we do not have policy name in our structures yet, only policyId)

**Comment by dsmf** [comment]
## PR Date filter createdOn and validUntil
https://github.com/eclipse-tractusx/item-relationship-service/pull/798

## PR Autocomplete
https://github.com/eclipse-tractusx/item-relationship-service/pull/799

**Comment by ds-kgassner** [comment]
Successfully tested: 
- Added possibility to filter by createdOn and validUntil to Policy Store API: GET /irs/policies/paged:
- Added autocomplete endpoint Policy Store API: GET /irs/policies/attributes/{attribute}.
- Added request to the insomnia IRS_Request_Collection, see "Policy attribute auto-complete"

**Comment by mkanal** [comment]
Merge is outstanding.
