### ISSUE TITLE
Tavern and Cucumber tests failed on Dev

### ISSUE THREAD

**Issue by ds-kgassner** [eclipse-tractusx/item-relationship-service#764]
## Description
Tavern and Cucumber tests failed on Dev.

## Current behaviour
The Tavern IRS API test on Dev WF encountered failures, with 25 tests failing, predominantly the ESS tests.

In the Cucumber tests, the following scenarios fail: 
- BomLifecycle 'asBuilt' for testing "JustInSequencePart-Model [BPNL00000000BJTL]
- End 2 End for aspects "3.0.0#Batch" with "1.0.0#PartSiteInformationAsBuilt"
- End 2 End for OEM-B (MB) [BPN:BPNL00000003AVTH] (SerialPart 3.0.0, SingleLevelBomAsBuilt 3.0.0 , Batch 3.0.0)
- End 2 End for Tier A (ZF) [BPN:BPNL00000003B2OM] (SerialPart 3.0.0, SingleLevelBomAsBuilt 3.0.0 , Batch 3.0.0)

## Expected behavior
Tavern and Cucumber tests on Dev ran successfull

## Steps to reproduce the Bug
Run WF actions for Tavern and Cucumber on Dev.

**Comment by mkanal** [comment]
Could not be reproduced. Flaky tests.
