### ISSUE TITLE
[SPIKE] Update EDC 0.7.3

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#794]
**As** product
**I want** to update on EDC 0.7.3
**so that** Store refresh token in vault bug is resolved 

## Hints / Details
- https://github.com/eclipse-tractusx/tractusx-edc/issues/1125

## Acceptance Criteria
- [x] IRS uses EDC version 0.7.3

## Out of Scope
- [x] Implementation 

Concerning the EDC version, we discussed and decided in today’s Test Daily:
 
The EDC version 0.7.3 has to be used for E2E Testing. If necessary, components need to be updated to this version.
 
 
Reasoning:
The version 0.7.1 is not standard compliant, that is the reason why it cannot be used in the further release process. Version 0.7.2 contains a serious bug concerning the EDR renewal. As experience shows, the update from 0.7.2 to 0.7.3 typically comes without problems.
 
The fix in 0.7.2 that ensures standard compliance has a breaking change impact in the management api. Details can be found in these items:
•	https://github.com/eclipse-edc/Connector/issues/4179
•	https://github.com/eclipse-edc/Connector/issues/4192

**Comment by ds-jhartmann** [comment]
Required policy update in https://github.com/eclipse-tractusx/item-relationship-service/pull/811
IRS is compatible with EDC 0.7.3 so no implementation changes have to be done

**Comment by ds-jhartmann** [comment]
Cucumber execution on DEV with EDC 0.7.3 was successful https://reports.cucumber.io/reports/2d17b927-d3f9-4bf3-ba83-e876b11da116

**Comment by mkanal** [comment]
LGFM. PO acceptance in behalf of @jzbmw
