### ISSUE TITLE
[IRS] QG 4 checks (Release 24.08)

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#817]
---
name: Quality Gate Checklist
about: 'product check for a upcoming Release'
title: 'QG X checks (Release x.x)'
labels: documentation
assignees: ''

---

## QG checks

Please open and fill in this issue in your product repository to document the compliance with our Tractus-X Release Guideline (TRGs)

**Show compliance with TRGs** by referencing to a tagged link in the respective repository where possible, example: TRG 1.01 (see [github.com/eclipse-tractusx/example-repo/tree/1.0.0/README.md](https://github.com/eclipse-tractusx/example-repo/tree/1.0.0/README.md))

### Close this issue once the compliance with the TRGs has been documented

Committer(s): https://github.com/eclipse-tractusx/item-relationship-service/blob/main/AUTHORS.md
Helm Chart Version: [item-relationship-service-7.4.0](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/item-relationship-service-7.4.0)
App Version: [5.4.0](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/5.4.0)

Release Management Reference Issue: 

### Check of Tractus-X Release Guidelines

- Currently implemented automatic checks can be found under your product on our [Release Guidelines Checks Board](https://eclipse-tractusx.github.io/sig-release/)
- This QG Check is depending on the mandatory information from our current [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)

#### TRG 1 Documentation

- [x] [TRG 1.01](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1) appropriate `README.md`
- [x] [TRG 1.02](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2) appropriate install instructions either `INSTALL.md` or in `README.md`
- [x] [TRG 1.03](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3) appropriate `CHANGELOG.md`
- [x] [TRG 1.04](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4) editable static files

#### TRG 2 Git

- [x] [TRG 2.01](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1) default branch is named `main`
- [x] [TRG 2.03](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3) repository structure
- [x] [TRG 2.04](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4) leading product repository
- [x] [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5) `.tractusx` metafile in a proper format
- [x] [TRG 2.06](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-6) Dependabot

#### TRG 3 Kubernetes

- [x] [TRG 3.02](https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2) persistent volume and persistent volume claim or database dependency (subchart) are in place when needed

#### TRG 4 Container

- [x] [TRG 4.07](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-07) root file system is set to read access by default, but can be overwritten by the user
- [x] [TRG 4.01](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-01) [semantic versioning](https://semver.org/) and tagging 
- [x] [TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02) base image is agreed  
- [x] [TRG 4.03](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03) image has `USER` command and Non Root Container
- [x] [TRG 4.05](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05) released image must be placed in `DockerHub`, remove `GHCR` references
- [x] [TRG 4.06](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06) separate notice file for `DockerHub` has all necessary information

#### TRG 5 Helm

- [x] [TRG 5.01](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01) Helm chart requirements
- [x] [TRG 5.02](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02) Helm chart location in `/charts` directory and correct structure
- [x] [TRG 5.03](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-03) proper version strategy 
- [x] [TRG 5.04](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04) CPU / MEM resource requests and limits and are properly set
- [x] [TRG 5.06](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06) Application must be configurable through the Helm chart 
- [x] [TRG 5.07](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07) Dependencies are present and properly configured in the Chart.yaml
- [x] [TRG 5.08](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08) Product has a single deployable helm chart that contains all components 
- [x] [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) Helm Test running properly
- [x] [TRG 5.10](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10) Products need to support 3 versions at a time
- [x] [TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11) Upgradeability
 
#### TRG 6 Released Helm Chart

- [x] [TRG 6.01](https://eclipse-tractusx.github.io/docs/release/trg-6/trg-6-1) Released Helm Chart 

#### TRG 7 Open Source Governance
- [x] [TRG 7.01](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01) Legal Documentation
- [x] [TRG 7.02](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) License and copyright header  
- [x] [TRG 7.03](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03) IP checks for project content 
- [x] [TRG 7.04](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04) IP checks for 3rd party content
- [x] [TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05) Legal information for distributions
- [x] [TRG 7.06](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06) Legal information for end user content
- [x] [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07) Legal notice for documentation
- [x] [TRG 7.08](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-08) Legal notice for KIT documentation

#### TRG 8 Security
- [x] [TRG 8.01](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-01) Mitigate high and above findings in CodeQL
- [x] [TRG 8.02](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-02) Mitigate high and above findings in KICS
- [x] [TRG 8.04](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-04) Mitigate high and above findings in Trivy
- [x] [TRG 8.03](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03) No secret findings by GitGuardian or TruffleHog

**Comment by mkanal** [comment]
Hi @ds-mwesener would you please proceed the TRG checks for IRS. Thank you very much.

**Comment by mkanal** [comment]
[TRG 1.01](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1) appropriate `README.md`
- [ ] Basic documentation of the repository, its content and its structure
- [ ] Installation instructions
- [ ] If required necessary step(s) to finish the installation
- [ ] Usage examples and intended use of your product
- [ ] License information
- [ ] Troubleshooting and FAQs to help users solve common problems
- [ ] Reference your Contribution guideline in the CONTRIBUTING.md file
- [ ] Contact information to help users getting in touch with you
- [ ] Badges to show the status of your project (e.g. build status, code coverage, etc.)

**Comment by mkanal** [comment]
[TRG 1.04](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4) editable static files
- [ ] These diagram code files (.puml,.mmd,.mermaid) and / or static diagram .svg files must be stored within the docs/ folder as described in [TRG 2.03](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3#docs).
- [ ] All digrams in documentation PUML was used for conceptional work mermaid is used as Github is able to render this instantly

**Comment by mkanal** [comment]
[TRG 2.03](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3) repository structure

- [ ] /docs
- [ ] /charts
- [ ] CODE_OF_CONDUCT.md
- [ ] CONTRIBUTING.md
- [ ] DEPENDENCIES
- [ ] LICENSE
- [ ] NOTICE.md
- [ ] README.md
- [ ] SECURITY.md
- [ ] AUTHORS.md
- [ ] INSTALL.md

**Comment by mkanal** [comment]
[TRG 2.06](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-6) Dependabot
-  [x] https://github.com/eclipse-tractusx/item-relationship-service/blob/main/.github/dependabot.yml

**Comment by mkanal** [comment]
[TRG 3.02](https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2) persistent volume and persistent volume claim or database dependency (subchart) are in place when needed

![image](https://github.com/user-attachments/assets/8527c1fe-bbf5-49bc-abc4-e1d11ecd7d5b)

**Comment by mkanal** [comment]
Open Checks 

- [ ] [TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02) base image is agreed  
- [ ] [TRG 4.03](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03) image has `USER` command and Non Root Container
- [ ] [TRG 4.05](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05) released image must be placed in `DockerHub`, remove `GHCR` references
- [x] [TRG 4.06](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06) separate notice file for `DockerHub` has all necessary information
- [ ] [TRG 4.07] (https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-07) root file system is set to read access by default, but can be overwritten by the user

**Comment by mkanal** [comment]
[TRG 7.01](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01) Legal Documentation
- [ ] LICENSE
- [ ] LICENSE_non-code
- [ ] NOTICE.md
- [ ] DEPENDENCIES
- [ ] SECURITY.md
- [ ] CONTRIBUTING.md
- [ ] CODE_OF_CONDUCT.md

**Comment by mkanal** [comment]
[TRG 7.03](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03) IP checks for project content
![image](https://github.com/user-attachments/assets/30fff352-a21c-4fe9-895a-f591e5b3ad92)

**Comment by mkanal** [comment]
[TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05) Legal information for distributions
- [ ] LICENSE
- [ ] NOTICE.md
- [ ] DEPENDENCIES file(s) - if existing
- [ ] SECURITY.md

**Comment by mkanal** [comment]
![image](https://github.com/user-attachments/assets/4ab92955-16c2-4ec4-aa7d-c11c087cddc4)

**Comment by ds-jhartmann** [comment]
#### TRG 4 Container

- [x] [TRG 4.07](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-07) See https://github.com/eclipse-tractusx/item-relationship-service/blob/main/charts/item-relationship-service/values.yaml
- [x] [TRG 4.01](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-01) [semantic versioning](https://semver.org/) See https://github.com/eclipse-tractusx/item-relationship-service/tags
- [x] [TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02) See https://github.com/eclipse-tractusx/item-relationship-service/blob/main/Dockerfile
- [x] [TRG 4.03](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03) See https://github.com/eclipse-tractusx/item-relationship-service/blob/main/Dockerfile
- [x] [TRG 4.05](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05) See https://github.com/eclipse-tractusx/item-relationship-service/blob/main/.github/workflows/irs-build.yml and https://hub.docker.com/r/tractusx/irs-api
- [x] [TRG 4.06](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06) See https://github.com/eclipse-tractusx/item-relationship-service/blob/main/DOCKER_NOTICE.md

#### TRG 5 Helm

- [x] [TRG 5.01](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01) See https://github.com/eclipse-tractusx/item-relationship-service/tree/main/charts/item-relationship-service
- [x] [TRG 5.02](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02) See https://github.com/eclipse-tractusx/item-relationship-service/tree/main/charts/item-relationship-service
- [x] [TRG 5.03](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-03) See https://github.com/eclipse-tractusx/item-relationship-service/blob/main/charts/item-relationship-service/Chart.yaml
- [x] [TRG 5.04](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04) See https://github.com/eclipse-tractusx/item-relationship-service/blob/main/charts/item-relationship-service/values.yaml
- [x] [TRG 5.06](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06) See https://github.com/eclipse-tractusx/item-relationship-service/tree/main/charts/item-relationship-service
- [x] [TRG 5.07](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07) See https://github.com/eclipse-tractusx/item-relationship-service/tree/main/charts/item-relationship-service
- [x] [TRG 5.08](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08) See https://github.com/eclipse-tractusx/item-relationship-service/tree/main/charts/item-relationship-service
- [x] [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) See https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/helm-test.yaml
- [x] [TRG 5.10](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10) See https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/helm-test-backwards-compatability.yaml and https://github.com/eclipse-tractusx/item-relationship-service/actions/runs/9939665825
- [x] [TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11) See https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/helm-upgrade.yaml
 
#### TRG 6 Released Helm Chart

- [x] [TRG 6.01](https://eclipse-tractusx.github.io/docs/release/trg-6/trg-6-1) See https://eclipse-tractusx.github.io/item-relationship-service/index.yaml

TRGs 4, 5 and 6 checked and verified

**Comment by ds-jhartmann** [comment]
@mkanal all QG checks are done, please verify and close this issue if everything looks good.

**Comment by mkanal** [comment]
LGFM all TRG passed.
