### ISSUE TITLE
Update OperationsView in KIT to latests version

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#823]
**As** product
**I want** installation procedure described in KIT is updated and working
**so that** contributors could use the installation procedure to install the project 

## Hints / Details
- https://eclipse-tractusx.github.io/docs-kits/kits/Data%20Chain%20Kit/Operation%20View/

## Acceptance Criteria
- [x] Operations view is updates to current state of deployment the irs 

## Out of Scope

- ...

**Comment by ds-jhartmann** [comment]
Update data chain kit operation view to latest IRS version in https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1009
