### ISSUE TITLE
Extend FAQ and Troubleshooting document

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#824]
## Hint 
- https://github.com/eclipse-tractusx/item-relationship-service/blob/main/FAQ.md

## Acceptance Criteria
- [x] FAQ and/or troubleshooting section answers the following Q:
   -  [x] How to reset / purge the minio database? 
   - [x]  How can a job that has hung up (no reaction) be canceled?
   - [x] Which resources are recommended for which use case? (cores/RAM)
   - [x] Can I autoscale irs across multiple pods? What do I have to do? 

## Out of Scope

- ...

**Comment by ds-jhartmann** [comment]
Added FAQ questions in https://github.com/eclipse-tractusx/item-relationship-service/pull/861
