### ISSUE TITLE
Reactivate Xray Tests in Jira of Association

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#828]
**As** testmanagement team
**I want** to execute tests in JIRA Xray
**so that** product could participate in e2e tests 

## Hints / Details

- ...

Trace-X A (BMW Trace-X) : BPNL000000000UKM
Trace-X B (Trace-X) BPNL000000000DWF formerly ...CNKC
DoubleSlash = BPNL000000000EVQ

## Acceptance Criteria
- [x] Tests are enabled in association xray 
- [x] Test executions are exported via ci cd pipeline 
- [x] Tests are executed 
- [x] Testdata is updated with new BPNLS 
- [x] Update test execution to current state 
- [x] Create Secrets for Jira technical user in Eclipse Github  organization (create ticket in Eclipse Helpdesk)

## Out of Scope

- ...

**Comment by dsmf** [comment]
PR #850

**Comment by ds-jhartmann** [comment]
Xray cucumber tests can be executed again via GH workflow https://github.com/eclipse-tractusx/item-relationship-service/actions/workflows/cucumber-integration-test-INT-association.yaml

Implemented in https://github.com/eclipse-tractusx/item-relationship-service/pull/850

**Comment by ds-kgassner** [comment]
Successfully tested 
![grafik](https://github.com/user-attachments/assets/e367c41b-dcdf-4915-8b60-d6e7201c6b39)

**Comment by ds-jhartmann** [comment]
Reqesting final approval @mkanal
