### ISSUE TITLE
🐞[R24.8] BusinessPartnerNumber and EndpointURL are not filled in tombstone

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#841]
## Current behavior
- Tombstone attribute BusinessPartnerNumber in null  (BusinessPartnerNumber  exisits for Tombstone )
- Tombstone attribute EndpointURL  is null (EndpointURL  exisits for Tombstone)

## Expected behavior
- BPN and EndpointURL attributes are filled when present 
 
## Steps to reproduce the Bug
- Execute scenario 

![Image](https://github.com/user-attachments/assets/f0995dd2-bab2-4728-bf70-d31f50fe7893)

**Comment by dsmf** [comment]
# PR with some cleanup first
https://github.com/eclipse-tractusx/item-relationship-service/pull/860
 
# PR for actual fix
TODO

**Comment by ds-jhartmann** [comment]
Fixed cucumber test in https://github.com/eclipse-tractusx/item-relationship-service/pull/866
Tested and works as expected. BPN and endpointURL are now filled for Tombstones during the Digital Twin request step
